In [ ]:
import pandas as pd
from numpy import *

## DataSet 1 – 1000 Cameras

Link: https://www.kaggle.com/datasets/crawford/1000-cameras-dataset

In [ ]:
# Reading the data into a dataframe

df1 = pd.read_csv("camera_dataset.csv")
df1

,Model,Release date,Max resolution,Low resolution,Effective pixels,Zoom wide (W),Zoom tele (T),Normal focus range,Macro focus range,Storage included,Weight (inc. batteries),Dimensions,Price
0,Agfa ePhoto 1280,1997,1024.0,640.0,0.0,38.0,114.0,70.0,40.0,4.0,420.0,95.0,179.0
1,Agfa ePhoto 1680,1998,1280.0,640.0,1.0,38.0,114.0,50.0,0.0,4.0,420.0,158.0,179.0
2,Agfa ePhoto CL18,2000,640.0,0.0,0.0,45.0,45.0,0.0,0.0,2.0,0.0,0.0,179.0
3,Agfa ePhoto CL30,1999,1152.0,640.0,0.0,35.0,35.0,0.0,0.0,4.0,0.0,0.0,269.0
4,Agfa ePhoto CL30 Clik!,1999,1152.0,640.0,0.0,43.0,43.0,50.0,0.0,40.0,300.0,128.0,1299.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1033,Toshiba PDR-M65,2001,2048.0,1024.0,3.0,38.0,114.0,10.0,10.0,8.0,320.0,120.0,62.0
1034,Toshiba PDR-M70,2000,2048.0,1024.0,3.0,35.0,105.0,80.0,9.0,16.0,390.0,116.0,62.0
1035,Toshiba PDR-M71,2001,2048.0,1024.0,3.0,35.0,98.0,80.0,10.0,8.0,340.0,107.0,62.0
1036,Toshiba PDR-M81,2001,2400.0,1200.0,3.0,35.0,98.0,80.0,10.0,16.0,340.0,107.0,62.0
1037,Toshiba PDR-T10,2002,1600.0,800.0,1.0,38.0,38.0,40.0,20.0,8.0,180.0,86.0,129.0

In [ ]:
# dropping non-numeric column

df1.drop(columns = ["Model"], inplace = True)
df1

,Release date,Max resolution,Low resolution,Effective pixels,Zoom wide (W),Zoom tele (T),Normal focus range,Macro focus range,Storage included,Weight (inc. batteries),Dimensions,Price
0,1997,1024.0,640.0,0.0,38.0,114.0,70.0,40.0,4.0,420.0,95.0,179.0
1,1998,1280.0,640.0,1.0,38.0,114.0,50.0,0.0,4.0,420.0,158.0,179.0
2,2000,640.0,0.0,0.0,45.0,45.0,0.0,0.0,2.0,0.0,0.0,179.0
3,1999,1152.0,640.0,0.0,35.0,35.0,0.0,0.0,4.0,0.0,0.0,269.0
4,1999,1152.0,640.0,0.0,43.0,43.0,50.0,0.0,40.0,300.0,128.0,1299.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1033,2001,2048.0,1024.0,3.0,38.0,114.0,10.0,10.0,8.0,320.0,120.0,62.0
1034,2000,2048.0,1024.0,3.0,35.0,105.0,80.0,9.0,16.0,390.0,116.0,62.0
1035,2001,2048.0,1024.0,3.0,35.0,98.0,80.0,10.0,8.0,340.0,107.0,62.0
1036,2001,2400.0,1200.0,3.0,35.0,98.0,80.0,10.0,16.0,340.0,107.0,62.0
1037,2002,1600.0,800.0,1.0,38.0,38.0,40.0,20.0,8.0,180.0,86.0,129.0

In [ ]:
# Dealing with NaN values

for col in df1:
    df1[col].replace({nan: df1[col].mean()}, inplace = True)

In [ ]:
df1.isna().sum() # Values removed successfully

Release date               0
Max resolution             0
Low resolution             0
Effective pixels           0
Zoom wide (W)              0
Zoom tele (T)              0
Normal focus range         0
Macro focus range          0
Storage included           0
Weight (inc. batteries)    0
Dimensions                 0
Price                      0
dtype: int64

In [ ]:
# Making an array

arr1 = df1.to_numpy()
arr1

array([[1997., 1024.,  640., ...,  420.,   95.,  179.],
       [1998., 1280.,  640., ...,  420.,  158.,  179.],
       [2000.,  640.,    0., ...,    0.,    0.,  179.],
       ...,
       [2001., 2048., 1024., ...,  340.,  107.,   62.],
       [2001., 2400., 1200., ...,  340.,  107.,   62.],
       [2002., 1600.,  800., ...,  180.,   86.,  129.]])

In [ ]:
arr1_t = arr1.transpose()
arr1_t

array([[1997., 1998., 2000., ..., 2001., 2001., 2002.],
       [1024., 1280.,  640., ..., 2048., 2400., 1600.],
       [ 640.,  640.,    0., ..., 1024., 1200.,  800.],
       ...,
       [ 420.,  420.,    0., ...,  340.,  340.,  180.],
       [  95.,  158.,    0., ...,  107.,  107.,   86.],
       [ 179.,  179.,  179., ...,   62.,   62.,  129.]])

In [ ]:
product1 = matmul(arr1, arr1_t)
product1

array([[ 5684607.,  5951733.,  4688249., ...,  6931106.,  7404226.,
         6264663.],
       [ 5951733.,  6290366.,  4854089., ...,  7462139.,  8025371.,
         6680084.],
       [ 4688249.,  4854089.,  4445695., ...,  5329819.,  5555115.,
         5054527.],
       ...,
       [ 6931106.,  7462139.,  5329819., ...,  9395176., 10296360.,
         8188923.],
       [ 7404226.,  8025371.,  5555115., ..., 10296360., 11352488.,
         8892987.],
       [ 6264663.,  6680084.,  5054527., ...,  8188923.,  8892987.,
         7269394.]])

In [ ]:
eigenvalues1, eigenvectors1 = linalg.eig(product1)
print(eigenvalues1)
print(eigenvectors1)

[1.50004641e+10+0.00000000e+00j 5.86953361e+08+0.00000000e+00j
 3.98251197e+08+0.00000000e+00j ... 7.84335302e-24+0.00000000e+00j
 1.63691339e-24+3.44161695e-24j 1.63691339e-24-3.44161695e-24j]
[[ 1.71725630e-02+0.00000000e+00j  2.56832710e-03+0.00000000e+00j
   5.21374432e-02+0.00000000e+00j ...  1.29533823e-15+0.00000000e+00j
   8.60868315e-16-3.58254590e-16j  8.60868315e-16+3.58254590e-16j]
 [ 1.86057146e-02+0.00000000e+00j  3.35733951e-03+0.00000000e+00j
   5.08837354e-02+0.00000000e+00j ... -7.40489438e-17+0.00000000e+00j
  -6.43560295e-17+1.61568232e-17j -6.43560295e-17-1.61568232e-17j]
 [ 1.21023602e-02+0.00000000e+00j  1.68433974e-03+0.00000000e+00j
   7.12121397e-02+0.00000000e+00j ...  7.30621248e-17+0.00000000e+00j
  -1.21836774e-16+7.91398436e-17j -1.21836774e-16-7.91398436e-17j]
 ...
 [ 2.42541840e-02+0.00000000e+00j  1.25081522e-02+0.00000000e+00j
   3.40582485e-02+0.00000000e+00j ...  3.48431165e-15+0.00000000e+00j
   1.61597845e-15-2.40427886e-16j  1.61597845e-15+2.40427886e-16j]
 [ 2.69255948e-02+0.00000000e+00j  1.42910811e-02+0.00000000e+00j
   2.65351829e-02+0.00000000e+00j ... -4.00940954e-15+0.00000000e+00j
  -2.33710662e-15+3.30811890e-16j -2.33710662e-15-3.30811890e-16j]
 [ 2.07981285e-02+0.00000000e+00j  8.54162173e-03+0.00000000e+00j
   4.22208304e-02+0.00000000e+00j ...  1.73762641e-15+0.00000000e+00j
   1.16938218e-15-2.67149071e-16j  1.16938218e-15+2.67149071e-16j]]

In [ ]:
# Remove the eigenvector with lowest eigenvalue

eigenvectors1 = delete(eigenvectors1, argmin(eigenvalues1), axis = 1)

In [ ]:
print(arr1.shape)
print(eigenvectors1.shape)

(1038, 12)
(1038, 1037)

In [ ]:
arr1 = insert(arr1, [12], zeros((1038, 1026)), axis = 1)

In [ ]:
# Multiplication now possible!

print(arr1.shape)
print(eigenvectors1.shape)

(1038, 1038)
(1038, 1037)

In [ ]:
PCA1 = matmul(arr1, eigenvectors1)
PCA1

array([[8.02214031e+01+0.00000000e+00j, 1.41052078e+01+0.00000000e+00j,
        2.41836151e+02+0.00000000e+00j, ...,
        2.63419633e-12+0.00000000e+00j, 1.59834806e-12-6.75500663e-13j,
        1.59834806e-12+6.75500663e-13j],
       [8.54209782e+01+0.00000000e+00j, 1.52988006e+01+0.00000000e+00j,
        2.53405354e+02+0.00000000e+00j, ...,
        2.65173354e-12+0.00000000e+00j, 1.59730240e-12-6.73152591e-13j,
        1.59730240e-12+6.73152591e-13j],
       [5.19683602e+01+0.00000000e+00j, 7.05818013e+00+0.00000000e+00j,
        1.47870834e+02+0.00000000e+00j, ...,
        2.62202826e-12+0.00000000e+00j, 1.74075644e-12-7.16675272e-13j,
        1.74075644e-12+7.16675272e-13j],
       ...,
       [9.96104372e+01+0.00000000e+00j, 1.69427383e+01+0.00000000e+00j,
        3.12282214e+02+0.00000000e+00j, ...,
        2.55202923e-12+0.00000000e+00j, 1.45404372e-12-6.15199923e-13j,
        1.45404372e-12+6.15199923e-13j],
       [1.08418345e+02+0.00000000e+00j, 1.84464510e+01+0.00000000e+00j,
        3.43154893e+02+0.00000000e+00j, ...,
        2.53752261e-12+0.00000000e+00j, 1.40979297e-12-5.95797223e-13j,
        1.40979297e-12+5.95797223e-13j],
       [8.46075721e+01+0.00000000e+00j, 1.36546706e+01+0.00000000e+00j,
        2.65132548e+02+0.00000000e+00j, ...,
        2.59663631e-12+0.00000000e+00j, 1.55182521e-12-6.45689581e-13j,
        1.55182521e-12+6.45689581e-13j]])

In [ ]:
U1, S1, V1 = linalg.svd(arr1, full_matrices = True)

In [ ]:
U1.shape, V1.shape, S1.shape

((1038, 1038), (1038, 1038), (1038,))

In [ ]:
print(U1)
print(V1)
print(S1)

[[-1.71725630e-02 -2.56832710e-03 -5.21374432e-02 ... -3.10707221e-02
  -2.75788004e-02 -3.39380288e-02]
 [-1.86057146e-02 -3.35733951e-03 -5.08837354e-02 ... -2.46006776e-02
  -1.01091871e-02 -3.06288462e-02]
 [-1.21023602e-02 -1.68433974e-03 -7.12121397e-02 ...  2.25183198e-02
   3.97663263e-02 -5.33899981e-03]
 ...
 [-2.42541840e-02 -1.25081522e-02 -3.40582485e-02 ...  9.95197947e-01
  -4.30608416e-03 -3.27335436e-04]
 [-2.69255948e-02 -1.42910811e-02 -2.65351829e-02 ... -4.53396419e-03
   9.93411036e-01 -1.05402282e-03]
 [-2.07981285e-02 -8.54162173e-03 -4.22208304e-02 ... -6.78148053e-04
  -1.16208636e-03  9.94186893e-01]]
[[-0.51150579 -0.67817069 -0.50244848 ...  0.          0.
   0.        ]
 [-0.08223116 -0.07674123 -0.09168106 ...  0.          0.
   0.        ]
 [-0.74708373  0.10879879  0.63540037 ...  0.          0.
   0.        ]
 ...
 [ 0.          0.          0.         ...  1.          0.
   0.        ]
 [ 0.          0.          0.         ...  0.          1.
   0.        ]
 [ 0.          0.          0.         ...  0.          0.
   1.        ]]
[1.22476382e+05 2.42271204e+04 1.99562320e+04 ... 9.98385477e-12
 9.98385477e-12 9.98385477e-12]

## DataSet 2 – 80 Cereals

Link: https://www.kaggle.com/datasets/crawford/80-cereals

In [ ]:
# Reading the data into a dataframe

df2 = pd.read_csv("cereal.csv")
df2

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,100% Bran,N,C,70,4,1,130,10.0,5.0,6,280,25,3,1.0,0.33,68.402973
1,100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8,135,0,3,1.0,1.00,33.983679
2,All-Bran,K,C,70,4,1,260,9.0,7.0,5,320,25,3,1.0,0.33,59.425505
3,All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8.0,0,330,25,3,1.0,0.50,93.704912
4,Almond Delight,R,C,110,2,2,200,1.0,14.0,8,-1,25,3,1.0,0.75,34.384843
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,Triples,G,C,110,2,1,250,0.0,21.0,3,60,25,3,1.0,0.75,39.106174
73,Trix,G,C,110,1,1,140,0.0,13.0,12,25,25,2,1.0,1.00,27.753301
74,Wheat Chex,R,C,100,3,1,230,3.0,17.0,3,115,25,1,1.0,0.67,49.787445
75,Wheaties,G,C,100,3,1,200,3.0,17.0,3,110,25,1,1.0,1.00,51.592193
76,Wheaties Honey Gold,G,C,110,2,1,200,1.0,16.0,8,60,25,1,1.0,0.75,36.187559

In [ ]:
# dropping non-numeric column

df2.drop(columns = ["name"], inplace = True)
df2

,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,N,C,70,4,1,130,10.0,5.0,6,280,25,3,1.0,0.33,68.402973
1,Q,C,120,3,5,15,2.0,8.0,8,135,0,3,1.0,1.00,33.983679
2,K,C,70,4,1,260,9.0,7.0,5,320,25,3,1.0,0.33,59.425505
3,K,C,50,4,0,140,14.0,8.0,0,330,25,3,1.0,0.50,93.704912
4,R,C,110,2,2,200,1.0,14.0,8,-1,25,3,1.0,0.75,34.384843
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,G,C,110,2,1,250,0.0,21.0,3,60,25,3,1.0,0.75,39.106174
73,G,C,110,1,1,140,0.0,13.0,12,25,25,2,1.0,1.00,27.753301
74,R,C,100,3,1,230,3.0,17.0,3,115,25,1,1.0,0.67,49.787445
75,G,C,100,3,1,200,3.0,17.0,3,110,25,1,1.0,1.00,51.592193
76,G,C,110,2,1,200,1.0,16.0,8,60,25,1,1.0,0.75,36.187559

In [ ]:
# Dealing with other non-numeric columns

df2["mfr"].value_counts()

K    23
G    22
P     9
Q     8
R     8
N     6
A     1
Name: mfr, dtype: int64

In [ ]:
df2["type"].value_counts()

C    74
H     3
Name: type, dtype: int64

In [ ]:
df2["mfr"] = df2["mfr"].replace({"K": 1, "G": 2, "P": 3, "Q": 4,
                    "R": 5, "N": 6, "A": 7})
df2["type"] = df2["type"].replace({"C": 0, "H": 1})
df2

,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,6,0,70,4,1,130,10.0,5.0,6,280,25,3,1.0,0.33,68.402973
1,4,0,120,3,5,15,2.0,8.0,8,135,0,3,1.0,1.00,33.983679
2,1,0,70,4,1,260,9.0,7.0,5,320,25,3,1.0,0.33,59.425505
3,1,0,50,4,0,140,14.0,8.0,0,330,25,3,1.0,0.50,93.704912
4,5,0,110,2,2,200,1.0,14.0,8,-1,25,3,1.0,0.75,34.384843
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,2,0,110,2,1,250,0.0,21.0,3,60,25,3,1.0,0.75,39.106174
73,2,0,110,1,1,140,0.0,13.0,12,25,25,2,1.0,1.00,27.753301
74,5,0,100,3,1,230,3.0,17.0,3,115,25,1,1.0,0.67,49.787445
75,2,0,100,3,1,200,3.0,17.0,3,110,25,1,1.0,1.00,51.592193
76,2,0,110,2,1,200,1.0,16.0,8,60,25,1,1.0,0.75,36.187559

In [ ]:
# Checking for NaN values

df2.isna().sum()

mfr         0
type        0
calories    0
protein     0
fat         0
sodium      0
fiber       0
carbo       0
sugars      0
potass      0
vitamins    0
shelf       0
weight      0
cups        0
rating      0
dtype: int64

In [ ]:
# Making an array

arr2 = df2.to_numpy()
arr2

array([[  6.      ,   0.      ,  70.      , ...,   1.      ,   0.33    ,
         68.402973],
       [  4.      ,   0.      , 120.      , ...,   1.      ,   1.      ,
         33.983679],
       [  1.      ,   0.      ,  70.      , ...,   1.      ,   0.33    ,
         59.425505],
       ...,
       [  5.      ,   0.      , 100.      , ...,   1.      ,   0.67    ,
         49.787445],
       [  2.      ,   0.      , 100.      , ...,   1.      ,   1.      ,
         51.592193],
       [  2.      ,   0.      , 110.      , ...,   1.      ,   0.75    ,
         36.187559]])

In [ ]:
arr2_t = arr2.transpose()
arr2_t

array([[  6.      ,   4.      ,   1.      , ...,   5.      ,   2.      ,
          2.      ],
       [  0.      ,   0.      ,   0.      , ...,   0.      ,   0.      ,
          0.      ],
       [ 70.      , 120.      ,  70.      , ..., 100.      , 100.      ,
        110.      ],
       ...,
       [  1.      ,   1.      ,   1.      , ...,   1.      ,   1.      ,
          1.      ],
       [  0.33    ,   1.      ,   0.33    , ...,   0.67    ,   1.      ,
          0.75    ],
       [ 68.402973,  33.983679,  59.425505, ...,  49.787445,  51.592193,
         36.187559]])

In [ ]:
product2 = matmul(arr2, arr2_t)
product2

array([[105728.07561524,  50633.91467708, 133177.99011403, ...,
         73310.83035607,  68116.38938479,  53763.58412121],
       [ 50633.91467708,  34197.89043838,  57664.82728633, ...,
         32871.63054911,  31796.29252582,  25747.53638885],
       [133177.99011403,  57664.82728633, 179239.49954451, ...,
        107366.86516178,  98071.22212308,  81851.71146829],
       ...,
       [ 73310.83035607,  32871.63054911, 107366.86516178, ...,
         79573.23857963,  72173.31347142,  66645.1886034 ],
       [ 68116.38938479,  31796.29252582,  98071.22212308, ...,
         72173.31347142,  65710.75437855,  60404.74552813],
       [ 53763.58412121,  25747.53638885,  81851.71146829, ...,
         66645.1886034 ,  60404.74552813,  57967.10192638]])

In [ ]:
eigenvalues2, eigenvectors2 = linalg.eig(product2)
print(eigenvalues2)
print(eigenvectors2)

[ 4.16436327e+06+0.00000000e+00j  4.46507656e+05+0.00000000e+00j
  1.17649740e+05+0.00000000e+00j  2.11768924e+04+0.00000000e+00j
  3.20111148e+04+0.00000000e+00j  8.09216708e+02+0.00000000e+00j
  4.24353749e+02+0.00000000e+00j  1.63735277e+02+0.00000000e+00j
  5.02232499e+01+0.00000000e+00j  4.34745855e+01+0.00000000e+00j
  2.28467445e+01+0.00000000e+00j  1.93861560e+01+0.00000000e+00j
  2.58016206e+00+0.00000000e+00j  1.59977134e+00+0.00000000e+00j
  2.76796818e-01+0.00000000e+00j  9.12270390e-11+0.00000000e+00j
 -1.97080055e-11+7.94478481e-11j -1.97080055e-11-7.94478481e-11j
 -5.45219169e-11+0.00000000e+00j  4.93480455e-11+0.00000000e+00j
 -4.52872613e-11+0.00000000e+00j  4.31327889e-11+0.00000000e+00j
  4.08537516e-11+7.28089874e-12j  4.08537516e-11-7.28089874e-12j
 -3.96555297e-11+0.00000000e+00j -3.54886668e-11+5.94275242e-12j
 -3.54886668e-11-5.94275242e-12j  3.59757931e-11+0.00000000e+00j
 -2.59621120e-11+1.15011898e-11j -2.59621120e-11-1.15011898e-11j
 -3.06721557e-11+0.00000000e+00j  3.20048967e-11+0.00000000e+00j
  3.09533373e-11+0.00000000e+00j  2.74336066e-11+0.00000000e+00j
 -2.50024564e-11+1.28695674e-12j -2.50024564e-11-1.28695674e-12j
 -2.46126689e-11+0.00000000e+00j  2.53302870e-11+0.00000000e+00j
 -2.06053803e-11+7.32883428e-13j -2.06053803e-11-7.32883428e-13j
  2.25006044e-11+0.00000000e+00j  2.17117975e-11+0.00000000e+00j
  9.70368990e-12+1.13872371e-11j  9.70368990e-12-1.13872371e-11j
  1.84967825e-11+2.57390363e-12j  1.84967825e-11-2.57390363e-12j
  1.70677183e-11+0.00000000e+00j -1.74114693e-11+0.00000000e+00j
 -1.52983316e-11+1.83947260e-12j -1.52983316e-11-1.83947260e-12j
  1.48901171e-11+0.00000000e+00j -1.31475987e-11+0.00000000e+00j
 -1.04639303e-11+3.27197425e-12j -1.04639303e-11-3.27197425e-12j
  1.21421481e-11+0.00000000e+00j  1.18309748e-11+0.00000000e+00j
  8.64251812e-12+1.40179144e-12j  8.64251812e-12-1.40179144e-12j
  8.48461577e-12+3.42657493e-13j  8.48461577e-12-3.42657493e-13j
 -8.59550072e-12+5.21560758e-13j -8.59550072e-12-5.21560758e-13j
 -7.74829621e-12+0.00000000e+00j -6.36762234e-12+0.00000000e+00j
  4.99683484e-12+0.00000000e+00j  4.02233727e-12+5.05282262e-13j
  4.02233727e-12-5.05282262e-13j -3.12703005e-12+1.42274918e-12j
 -3.12703005e-12-1.42274918e-12j -4.37304225e-12+0.00000000e+00j
 -3.85834466e-12+0.00000000e+00j -1.72560167e-12+6.56082492e-13j
 -1.72560167e-12-6.56082492e-13j  1.61643333e-12+1.47428484e-12j
  1.61643333e-12-1.47428484e-12j  1.46294252e-12+0.00000000e+00j
  9.88193420e-13+0.00000000e+00j]
[[-0.12989586+0.j          0.26564198+0.j         -0.17660507+0.j
  ...  0.00411558+0.0071753j   0.00398077+0.j
   0.00322204+0.j        ]
 [-0.06349172+0.j          0.17093721+0.j          0.17249209+0.j
  ... -0.00352208-0.00203419j  0.00042165+0.j
   0.00098916+0.j        ]
 [-0.18552086+0.j          0.21145404+0.j         -0.36686998+0.j
  ...  0.03549812+0.00176474j -0.01194092+0.j
   0.01790905+0.j        ]
 ...
 [-0.13720771+0.j         -0.0225635 +0.j         -0.07758335+0.j
  ... -0.03512127+0.02626188j  0.02904618+0.j
  -0.02173768+0.j        ]
 [-0.12523069+0.j         -0.00488274+0.j         -0.03801216+0.j
  ...  0.0741468 +0.04517816j -0.03727344+0.j
   0.05345926+0.j        ]
 [-0.1156097 +0.j         -0.07023078+0.j          0.02039514+0.j
  ...  0.01514001+0.02283218j  0.07145232+0.j
  -0.05147209+0.j        ]]

In [ ]:
# Remove the eigenvector with lowest eigenvalue

eigenvectors2 = delete(eigenvectors2, argmin(eigenvalues2), axis = 1)

In [ ]:
print(arr2.shape)
print(eigenvectors2.shape)

(77, 15)
(77, 76)

In [ ]:
arr2 = insert(arr2, [15], zeros((77, 62)), axis = 1)

In [ ]:
# Multiplication now possible!

print(arr2.shape)
print(eigenvectors2.shape)

(77, 77)
(77, 76)

In [ ]:
PCA2 = matmul(arr2, eigenvectors2)
PCA2

array([[ -81.99304162 +0.j        ,   28.18737727 +0.j        ,
         -61.14618929 +0.j        , ...,   -6.07286593-33.47784022j,
          -3.88798761 +0.j        ,    8.08986517 +0.j        ],
       [ -51.29271636 +0.j        ,   35.16114407 +0.j        ,
         -63.64976953 +0.j        , ...,    9.02007081 -9.04304229j,
           5.9331335  +0.j        ,   -0.98393924 +0.j        ],
       [-100.4524153  +0.j        ,   25.29378124 +0.j        ,
         -62.90299743 +0.j        , ...,  -18.41869713-53.51945078j,
         -23.23434206 +0.j        ,   28.31974592 +0.j        ],
       ...,
       [ -72.92757089 +0.j        ,   16.52846879 +0.j        ,
         -45.75083228 +0.j        , ...,  -23.26089638-45.53609833j,
         -32.13301124 +0.j        ,   31.3929841  +0.j        ],
       [ -68.75501943 +0.j        ,   16.48723626 +0.j        ,
         -45.22612297 +0.j        , ...,  -20.23637175-41.06592662j,
         -27.44989832 +0.j        ,   26.64415295 +0.j        ],
       [ -61.96034798 +0.j        ,   15.0629737  +0.j        ,
         -42.57471825 +0.j        , ...,  -21.7228685 -37.10948869j,
         -30.0717935  +0.j        ,   28.2484589  +0.j        ]])

In [ ]:
U2, S2, V2 = linalg.svd(arr2, full_matrices = True)

In [ ]:
U2.shape, V2.shape, S2.shape

((77, 77), (77, 77), (77,))

In [ ]:
print(U2)
print(V2)
print(S2)

[[-0.12989586 -0.26564198 -0.17660507 ... -0.17726963 -0.08467972
  -0.05261221]
 [-0.06349172 -0.17093721  0.17249209 ...  0.05457514  0.0424297
   0.10212164]
 [-0.18552086 -0.21145404 -0.36686998 ...  0.10301473 -0.03983589
  -0.00872795]
 ...
 [-0.13720771  0.0225635  -0.07758335 ...  0.90163883 -0.02785493
  -0.0381549 ]
 [-0.12523069  0.00488274 -0.03801216 ... -0.03867286  0.91491637
  -0.0520524 ]
 [-0.1156097   0.07023078  0.02039514 ... -0.05713048 -0.0411207
   0.93056498]]
[[-1.02573190e-02 -7.60139227e-05 -4.45925228e-01 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-7.92738746e-03 -3.63238533e-04 -3.60262234e-02 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 2.95776016e-02  1.69483897e-03  8.09828259e-01 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 ...
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  1.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  1.00000000e+00]]
[2.04067716e+03 6.68212284e+02 3.43001079e+02 1.78916502e+02
 1.45522824e+02 2.84467346e+01 2.05998483e+01 1.27959086e+01
 7.08683638e+00 6.59352603e+00 4.77982683e+00 4.40297127e+00
 1.60628829e+00 1.26482067e+00 5.26114834e-01 1.53395575e-13
 1.53395575e-13 1.53395575e-13 1.53395575e-13 1.53395575e-13
 1.53395575e-13 1.53395575e-13 1.53395575e-13 1.53395575e-13
 1.53395575e-13 1.53395575e-13 1.53395575e-13 1.53395575e-13
 1.53395575e-13 1.53395575e-13 1.53395575e-13 1.53395575e-13
 1.53395575e-13 1.53395575e-13 1.53395575e-13 1.53395575e-13
 1.53395575e-13 1.53395575e-13 1.53395575e-13 1.53395575e-13
 1.53395575e-13 1.53395575e-13 1.53395575e-13 1.53395575e-13
 1.53395575e-13 1.53395575e-13 1.53395575e-13 1.53395575e-13
 1.53395575e-13 1.53395575e-13 1.53395575e-13 1.53395575e-13
 1.53395575e-13 1.53395575e-13 1.53395575e-13 1.53395575e-13
 1.53395575e-13 1.53395575e-13 1.53395575e-13 1.53395575e-13
 1.53395575e-13 1.53395575e-13 1.53395575e-13 1.53395575e-13
 1.53395575e-13 1.53395575e-13 1.53395575e-13 1.53395575e-13
 1.53395575e-13 1.53395575e-13 1.53395575e-13 1.53395575e-13
 1.53395575e-13 1.53395575e-13 1.53395575e-13 1.53395575e-13
 1.53395575e-13]

## DataSet 3 – GroundHog Day Forecasts and Temperatures

Link: https://www.kaggle.com/datasets/groundhogclub/groundhog-day

In [ ]:
# Reading the data into a dataframe

df3 = pd.read_csv("groundhog.csv")
df3

,Year,Punxsutawney Phil,February Average Temperature,February Average Temperature (Northeast),February Average Temperature (Midwest),February Average Temperature (Pennsylvania),March Average Temperature,March Average Temperature (Northeast),March Average Temperature (Midwest),March Average Temperature (Pennsylvania)
0,1886,No Record,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1887,Full Shadow,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1888,Full Shadow,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1889,No Record,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1890,No Shadow,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
127,2013,No Shadow,34.77,25.3,33.4,27.4,40.91,32.7,37.3,33.9
128,2014,Full Shadow,32.13,21.0,27.1,22.8,40.51,26.0,38.0,30.3
129,2015,Full Shadow,32.99,12.1,23.4,16.1,45.39,27.8,41.6,31.6
130,2016,No Shadow,39.47,28.1,36.9,30.8,47.50,38.8,49.5,43.4
131,1901-2000,NaN,33.82,22.5,32.9,26.5,41.50,32.3,42.4,35.9

In [ ]:
# Dealing with non-numeric column

df3["Punxsutawney Phil"].value_counts()

Full Shadow       102
No Shadow          16
No Record          12
Partial Shadow      1
Name: Punxsutawney Phil, dtype: int64

In [ ]:
df3["Punxsutawney Phil"] = df3["Punxsutawney Phil"].replace({"No Record": 0, "No Shadow": 1,
                                                             "Partial Shadow": 2, "Full Shadow": 3})
df3

,Year,Punxsutawney Phil,February Average Temperature,February Average Temperature (Northeast),February Average Temperature (Midwest),February Average Temperature (Pennsylvania),March Average Temperature,March Average Temperature (Northeast),March Average Temperature (Midwest),March Average Temperature (Pennsylvania)
0,1886,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1887,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1888,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1889,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1890,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
127,2013,1.0,34.77,25.3,33.4,27.4,40.91,32.7,37.3,33.9
128,2014,3.0,32.13,21.0,27.1,22.8,40.51,26.0,38.0,30.3
129,2015,3.0,32.99,12.1,23.4,16.1,45.39,27.8,41.6,31.6
130,2016,1.0,39.47,28.1,36.9,30.8,47.50,38.8,49.5,43.4
131,1901-2000,NaN,33.82,22.5,32.9,26.5,41.50,32.3,42.4,35.9

In [ ]:
# Dropping the last row (contains total of the stats from 1901 to 2000)

df3.drop(index = 131, axis = 0, inplace = True)
df3

,Year,Punxsutawney Phil,February Average Temperature,February Average Temperature (Northeast),February Average Temperature (Midwest),February Average Temperature (Pennsylvania),March Average Temperature,March Average Temperature (Northeast),March Average Temperature (Midwest),March Average Temperature (Pennsylvania)
0,1886,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1887,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1888,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1889,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1890,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
126,2012,3.0,37.51,30.6,38.6,34.3,50.41,43.4,56.3,47.7
127,2013,1.0,34.77,25.3,33.4,27.4,40.91,32.7,37.3,33.9
128,2014,3.0,32.13,21.0,27.1,22.8,40.51,26.0,38.0,30.3
129,2015,3.0,32.99,12.1,23.4,16.1,45.39,27.8,41.6,31.6
130,2016,1.0,39.47,28.1,36.9,30.8,47.50,38.8,49.5,43.4

In [ ]:
df3.dtypes

Year                                            object
Punxsutawney Phil                              float64
February Average Temperature                   float64
February Average Temperature (Northeast)       float64
February Average Temperature (Midwest)         float64
February Average Temperature (Pennsylvania)    float64
March Average Temperature                      float64
March Average Temperature (Northeast)          float64
March Average Temperature (Midwest)            float64
March Average Temperature (Pennsylvania)       float64
dtype: object

In [ ]:
df3["Year"] = df3["Year"].astype('float64') # Typecasting

In [ ]:
# Dealing with NaN values

for col in df3:
    df3[col].replace({nan: df3[col].mean()}, inplace = True)

In [ ]:
df3.isna().sum() # Values removed successfully

Year                                           0
Punxsutawney Phil                              0
February Average Temperature                   0
February Average Temperature (Northeast)       0
February Average Temperature (Midwest)         0
February Average Temperature (Pennsylvania)    0
March Average Temperature                      0
March Average Temperature (Northeast)          0
March Average Temperature (Midwest)            0
March Average Temperature (Pennsylvania)       0
dtype: int64

In [ ]:
# Making an array

arr3 = df3.to_numpy()
arr3

array([[1.88600000e+03, 0.00000000e+00, 3.38027049e+01, ...,
        3.23680328e+01, 4.25688525e+01, 3.59081967e+01],
       [1.88700000e+03, 3.00000000e+00, 3.38027049e+01, ...,
        3.23680328e+01, 4.25688525e+01, 3.59081967e+01],
       [1.88800000e+03, 3.00000000e+00, 3.38027049e+01, ...,
        3.23680328e+01, 4.25688525e+01, 3.59081967e+01],
       ...,
       [2.01400000e+03, 3.00000000e+00, 3.21300000e+01, ...,
        2.60000000e+01, 3.80000000e+01, 3.03000000e+01],
       [2.01500000e+03, 3.00000000e+00, 3.29900000e+01, ...,
        2.78000000e+01, 4.16000000e+01, 3.16000000e+01],
       [2.01600000e+03, 1.00000000e+00, 3.94700000e+01, ...,
        3.88000000e+01, 4.95000000e+01, 4.34000000e+01]])

In [ ]:
arr3_t = arr3.transpose()
arr3_t

array([[1.88600000e+03, 1.88700000e+03, 1.88800000e+03, ...,
        2.01400000e+03, 2.01500000e+03, 2.01600000e+03],
       [0.00000000e+00, 3.00000000e+00, 3.00000000e+00, ...,
        3.00000000e+00, 3.00000000e+00, 1.00000000e+00],
       [3.38027049e+01, 3.38027049e+01, 3.38027049e+01, ...,
        3.21300000e+01, 3.29900000e+01, 3.94700000e+01],
       ...,
       [3.23680328e+01, 3.23680328e+01, 3.23680328e+01, ...,
        2.60000000e+01, 2.78000000e+01, 3.88000000e+01],
       [4.25688525e+01, 4.25688525e+01, 4.25688525e+01, ...,
        3.80000000e+01, 4.16000000e+01, 4.95000000e+01],
       [3.59081967e+01, 3.59081967e+01, 3.59081967e+01, ...,
        3.03000000e+01, 3.16000000e+01, 4.34000000e+01]])

In [ ]:
product3 = matmul(arr3, arr3_t)
product3

array([[3566314.00021119, 3568200.00021119, 3570086.00021119, ...,
        3806693.81175164, 3808569.92008115, 3813073.36055   ],
       [3568200.00021119, 3570096.00021119, 3571983.00021119, ...,
        3808716.81175164, 3810593.92008115, 3815092.36055   ],
       [3570086.00021119, 3571983.00021119, 3573871.00021119, ...,
        3810730.81175164, 3812608.92008115, 3817108.36055   ],
       ...,
       [3806693.81175164, 3808716.81175164, 3810730.81175164, ...,
        4063611.737     , 4065634.1176    , 4069916.5461    ],
       [3808569.92008115, 3810593.92008115, 3812608.92008115, ...,
        4065634.1176    , 4067837.7322    , 4071909.7703    ],
       [3813073.36055   , 3815092.36055   , 3817108.36055   , ...,
        4069916.5461    , 4071909.7703    , 4077010.2409    ]])

In [ ]:
eigenvalues3, eigenvectors3 = linalg.eig(product3)
print(eigenvalues3)
print(eigenvectors3)

[ 5.00047899e+08+0.00000000e+00j  7.86122583e+03+0.00000000e+00j
  5.80525791e+03+0.00000000e+00j  1.01559321e+03+0.00000000e+00j
  6.23380359e+02+0.00000000e+00j  3.06166586e+02+0.00000000e+00j
  1.29015971e+02+0.00000000e+00j  1.17510070e+02+0.00000000e+00j
  3.29865344e+01+0.00000000e+00j  2.61799236e+01+0.00000000e+00j
 -5.24508731e-08+0.00000000e+00j  3.29855949e-08+2.39577475e-08j
  3.29855949e-08-2.39577475e-08j -1.41416563e-08+3.67980495e-08j
 -1.41416563e-08-3.67980495e-08j  1.79011999e-08+1.96646461e-08j
  1.79011999e-08-1.96646461e-08j  1.10396024e-08+2.27499893e-08j
  1.10396024e-08-2.27499893e-08j -1.84074655e-08+1.66716908e-08j
 -1.84074655e-08-1.66716908e-08j -1.28022872e-09+2.46159352e-08j
 -1.28022872e-09-2.46159352e-08j -6.82659859e-09+2.28653452e-08j
 -6.82659859e-09-2.28653452e-08j -2.24545001e-08+5.34518548e-09j
 -2.24545001e-08-5.34518548e-09j  2.08793298e-08+0.00000000e+00j
  1.81736088e-08+7.00468491e-09j  1.81736088e-08-7.00468491e-09j
 -1.08683730e-08+1.55426981e-08j -1.08683730e-08-1.55426981e-08j
 -1.85533693e-08+0.00000000e+00j  9.41073697e-09+1.00573349e-08j
  9.41073697e-09-1.00573349e-08j -1.18954127e-08+9.94073969e-10j
 -1.18954127e-08-9.94073969e-10j -1.02662830e-08+7.25267483e-10j
 -1.02662830e-08-7.25267483e-10j -5.84706632e-09+7.26473632e-09j
 -5.84706632e-09-7.26473632e-09j  1.03792552e-08+0.00000000e+00j
  6.36948609e-09+7.00330621e-09j  6.36948609e-09-7.00330621e-09j
  8.94560625e-09+3.77545551e-09j  8.94560625e-09-3.77545551e-09j
 -8.30640524e-09+3.20762062e-09j -8.30640524e-09-3.20762062e-09j
 -2.59586163e-09+8.08276819e-09j -2.59586163e-09-8.08276819e-09j
 -6.89868525e-09+4.17024698e-09j -6.89868525e-09-4.17024698e-09j
 -5.56980030e-09+5.68449022e-09j -5.56980030e-09-5.68449022e-09j
  8.82113117e-09+0.00000000e+00j  1.68536787e-09+7.65454380e-09j
  1.68536787e-09-7.65454380e-09j -7.58462167e-09+1.56482939e-09j
 -7.58462167e-09-1.56482939e-09j  7.87118536e-09+2.53693162e-09j
  7.87118536e-09-2.53693162e-09j -7.64350156e-09+0.00000000e+00j
  8.18907282e-09+0.00000000e+00j  2.83436672e-09+6.60280782e-09j
  2.83436672e-09-6.60280782e-09j  1.07435083e-10+6.96813102e-09j
  1.07435083e-10-6.96813102e-09j  7.72035720e-09+7.64786520e-10j
  7.72035720e-09-7.64786520e-10j  6.17802238e-09+3.81817409e-09j
  6.17802238e-09-3.81817409e-09j  3.88839357e-09+5.43940805e-09j
  3.88839357e-09-5.43940805e-09j  6.87252308e-09+1.51910586e-09j
  6.87252308e-09-1.51910586e-09j -1.85813984e-09+5.80098980e-09j
 -1.85813984e-09-5.80098980e-09j -6.07296958e-09+2.07758075e-09j
 -6.07296958e-09-2.07758075e-09j -4.87689409e-09+3.71442168e-09j
 -4.87689409e-09-3.71442168e-09j -3.26156172e-09+4.86729757e-09j
 -3.26156172e-09-4.86729757e-09j -5.89175962e-09+0.00000000e+00j
 -4.32019619e-09+3.56020630e-09j -4.32019619e-09-3.56020630e-09j
  5.16799061e-09+2.64071459e-09j  5.16799061e-09-2.64071459e-09j
  3.30018400e-09+4.36516256e-09j  3.30018400e-09-4.36516256e-09j
  1.30877451e-09+4.89667599e-09j  1.30877451e-09-4.89667599e-09j
 -4.47141161e-09+0.00000000e+00j -2.40978196e-09+4.01785238e-09j
 -2.40978196e-09-4.01785238e-09j  4.64601282e-09+1.47634653e-09j
  4.64601282e-09-1.47634653e-09j  3.19180041e-09+3.40773343e-09j
  3.19180041e-09-3.40773343e-09j  2.25001412e-10+3.94077409e-09j
  2.25001412e-10-3.94077409e-09j -3.95724865e-09+8.59416647e-10j
 -3.95724865e-09-8.59416647e-10j  1.35207618e-09+3.74664936e-09j
  1.35207618e-09-3.74664936e-09j -3.78570919e-09+0.00000000e+00j
 -3.01788605e-09+1.94488910e-09j -3.01788605e-09-1.94488910e-09j
  4.38482461e-09+0.00000000e+00j  2.16752893e-09+2.82062745e-09j
  2.16752893e-09-2.82062745e-09j -2.98281833e-09+0.00000000e+00j
  3.94424518e-09+0.00000000e+00j -2.37065972e-09+1.38109187e-09j
 -2.37065972e-09-1.38109187e-09j -7.79022774e-10+2.70102155e-09j
 -7.79022774e-10-2.70102155e-09j -1.17545329e-09+2.34566175e-09j
 -1.17545329e-09-2.34566175e-09j  3.21093424e-09+0.00000000e+00j
  2.32410755e-09+1.31639573e-09j  2.32410755e-09-1.31639573e-09j
  1.44057915e-09+1.62362203e-09j  1.44057915e-09-1.62362203e-09j
 -6.96871016e-10+2.08029784e-09j -6.96871016e-10-2.08029784e-09j
 -1.51356202e-09+0.00000000e+00j  1.00613218e-09+0.00000000e+00j
  4.39627099e-10+2.46654245e-10j  4.39627099e-10-2.46654245e-10j
 -8.76153228e-10+0.00000000e+00j]
[[ 0.08445065+0.j          0.0318243 +0.j         -0.01562002+0.j
  ... -0.04747472+0.00557783j -0.04747472-0.00557783j
  -0.15025675+0.j        ]
 [ 0.08449549+0.j          0.03141703+0.j         -0.01533646+0.j
  ... -0.00370128+0.00117799j -0.00370128-0.00117799j
  -0.01759825+0.j        ]
 [ 0.08454015+0.j          0.03092432+0.j         -0.01509958+0.j
  ... -0.03509889+0.01082459j -0.03509889-0.01082459j
   0.05503712+0.j        ]
 ...
 [ 0.09014434+0.j         -0.15202855+0.j          0.0729801 +0.j
  ...  0.02883823+0.02080728j  0.02883823-0.02080728j
   0.0607916 +0.j        ]
 [ 0.09018878+0.j         -0.21989484+0.j         -0.05708878+0.j
  ...  0.02113641+0.00188382j  0.02113641-0.00188382j
   0.02442141+0.j        ]
 [ 0.09029326+0.j          0.1340381 +0.j         -0.07027002+0.j
  ...  0.05515743+0.0547283j   0.05515743-0.0547283j
   0.08527543+0.j        ]]

In [ ]:
# Remove the eigenvector with lowest eigenvalue

eigenvectors3 = delete(eigenvectors3, argmin(eigenvalues3), axis = 1)

In [ ]:
print(arr3.shape)
print(eigenvectors3.shape)

(131, 10)
(131, 130)

In [ ]:
arr3 = insert(arr3, [10], zeros((131, 121)), axis = 1)

In [ ]:
# Multiplication now possible!

print(arr3.shape)
print(eigenvectors3.shape)

(131, 131)
(131, 130)

In [ ]:
PCA3 = matmul(arr3, eigenvectors3)
PCA3

array([[ 181.99598505 +0.j        ,   60.30144813 +0.j        ,
         -34.79110218 +0.j        , ...,  -90.43928412 +9.99114557j,
         -90.43928412 -9.99114557j, -281.23740143 +0.j        ],
       [ 182.33392217 +0.j        ,   60.42752351 +0.j        ,
         -34.85273158 +0.j        , ...,  -90.49786268+10.00025738j,
         -90.49786268-10.00025738j, -281.44045293 +0.j        ],
       [ 182.41837282 +0.j        ,   60.45934781 +0.j        ,
         -34.8683516  +0.j        , ...,  -90.5453374 +10.0058352j ,
         -90.5453374 -10.0058352j , -281.59070968 +0.j        ],
       ...,
       [ 190.48216942 +0.j        ,   64.76520043 +0.j        ,
         -36.1705142  +0.j        , ...,  -96.53440068+10.8798948j ,
         -96.53440068-10.8798948j , -300.60107371 +0.j        ],
       [ 189.98765025 +0.j        ,   64.30261272 +0.j        ,
         -36.13144942 +0.j        , ...,  -96.83178947+10.91191377j,
         -96.83178947-10.91191377j, -300.35204731 +0.j        ],
       [ 196.97347906 +0.j        ,   64.24392825 +0.j        ,
         -37.80965284 +0.j        , ...,  -96.8204023 +10.62856169j,
         -96.8204023 -10.62856169j, -300.40739677 +0.j        ]])

In [ ]:
U3, S3, V3 = linalg.svd(arr3, full_matrices = True)

In [ ]:
U3.shape, V3.shape, S3.shape

((131, 131), (131, 131), (131,))

In [ ]:
print(U3)
print(V3)
print(S3)

[[-0.08445065 -0.0318243  -0.01562002 ... -0.06388922 -0.07602169
  -0.05178647]
 [-0.08449549 -0.03141703 -0.01533646 ...  0.13393831  0.16865568
  -0.16758452]
 [-0.08454015 -0.03092432 -0.01509958 ... -0.01962581 -0.28155194
  -0.0598212 ]
 ...
 [-0.09014434  0.15202855  0.0729801  ...  0.91938427 -0.04816783
  -0.00788458]
 [-0.09018878  0.21989484 -0.05708878 ... -0.0468498   0.85269386
  -0.00338733]
 [-0.09029326 -0.1340381  -0.07027002 ... -0.0089384  -0.0021117
   0.91684257]]
[[-0.99877731 -0.00126755 -0.01730764 ...  0.          0.
   0.        ]
 [ 0.04368526 -0.00252497 -0.26718062 ...  0.          0.
   0.        ]
 [ 0.01804829  0.00118576  0.16041125 ...  0.          0.
   0.        ]
 ...
 [ 0.          0.          0.         ...  1.          0.
   0.        ]
 [ 0.          0.          0.         ...  0.          1.
   0.        ]
 [ 0.          0.          0.         ...  0.          0.
   1.        ]]
[2.23617508e+04 8.86635541e+01 7.61922431e+01 3.18683732e+01
 2.49675862e+01 1.74976166e+01 1.13585198e+01 1.08402062e+01
 5.74339050e+00 5.11663206e+00 2.23165584e-12 2.23165584e-12
 2.23165584e-12 2.23165584e-12 2.23165584e-12 2.23165584e-12
 2.23165584e-12 2.23165584e-12 2.23165584e-12 2.23165584e-12
 2.23165584e-12 2.23165584e-12 2.23165584e-12 2.23165584e-12
 2.23165584e-12 2.23165584e-12 2.23165584e-12 2.23165584e-12
 2.23165584e-12 2.23165584e-12 2.23165584e-12 2.23165584e-12
 2.23165584e-12 2.23165584e-12 2.23165584e-12 2.23165584e-12
 2.23165584e-12 2.23165584e-12 2.23165584e-12 2.23165584e-12
 2.23165584e-12 2.23165584e-12 2.23165584e-12 2.23165584e-12
 2.23165584e-12 2.23165584e-12 2.23165584e-12 2.23165584e-12
 2.23165584e-12 2.23165584e-12 2.23165584e-12 2.23165584e-12
 2.23165584e-12 2.23165584e-12 2.23165584e-12 2.23165584e-12
 2.23165584e-12 2.23165584e-12 2.23165584e-12 2.23165584e-12
 2.23165584e-12 2.23165584e-12 2.23165584e-12 2.23165584e-12
 2.23165584e-12 2.23165584e-12 2.23165584e-12 2.23165584e-12
 2.23165584e-12 2.23165584e-12 2.23165584e-12 2.23165584e-12
 2.23165584e-12 2.23165584e-12 2.23165584e-12 2.23165584e-12
 2.23165584e-12 2.23165584e-12 2.23165584e-12 2.23165584e-12
 2.23165584e-12 2.23165584e-12 2.23165584e-12 2.23165584e-12
 2.23165584e-12 2.23165584e-12 2.23165584e-12 2.23165584e-12
 2.23165584e-12 2.23165584e-12 2.23165584e-12 2.23165584e-12
 2.23165584e-12 2.23165584e-12 2.23165584e-12 2.23165584e-12
 2.23165584e-12 2.23165584e-12 2.23165584e-12 2.23165584e-12
 2.23165584e-12 2.23165584e-12 2.23165584e-12 2.23165584e-12
 2.23165584e-12 2.23165584e-12 2.23165584e-12 2.23165584e-12
 2.23165584e-12 2.23165584e-12 2.23165584e-12 2.23165584e-12
 2.23165584e-12 2.23165584e-12 2.23165584e-12 2.23165584e-12
 2.23165584e-12 2.23165584e-12 2.23165584e-12 2.23165584e-12
 2.23165584e-12 2.23165584e-12 2.23165584e-12 2.23165584e-12
 2.23165584e-12 2.23165584e-12 2.23165584e-12 2.23165584e-12
 2.23165584e-12 2.23165584e-12 2.23165584e-12]

## DataSet 4 – USA Poverty Level Wages

Link: https://www.kaggle.com/datasets/asaniczka/poverty-level-wages-in-the-usa-dataset-1973-2022

In [ ]:
# Reading the data into a dataframe

df4 = pd.read_csv("poverty_level_wages.csv")
df4

,year,annual_poverty-level_wage,hourly_poverty-level_wage,0-75%_of_poverty_wages,75-100%_of_poverty_wages,share_below_poverty_wages,100-125%_of_poverty_wages,125-200%_of_poverty_wages,200-300%_of_poverty_wages,300%+_of_poverty_wages,...,women_300%+_of_poverty_wages,white_share_below_poverty_wages,white_men_share_below_poverty_wages,white_women_share_below_poverty_wages,black_share_below_poverty_wages,black_men_share_below_poverty_wages,black_women_share_below_poverty_wages,hispanic_share_below_poverty_wages,hispanic_men_share_below_poverty_wages,hispanic_women_share_below_poverty_wages
0,2022,27733,13.33,4.7,7.5,12.2,15.2,32.7,19.5,20.4,...,16.7,10.7,8.1,13.5,16.2,14.5,17.7,15.4,12.3,19.2
1,2021,25688,12.35,3.8,9.1,12.9,15.0,30.3,20.4,21.5,...,17.4,11.1,8.7,13.8,18.0,15.7,19.9,16.8,14.2,20.0
2,2020,24544,11.80,3.4,8.6,12.0,13.0,31.5,20.8,22.6,...,18.1,10.4,7.9,13.1,18.1,15.4,20.5,14.9,12.0,18.6
3,2019,24242,11.65,4.4,11.3,15.7,14.2,31.2,18.7,20.3,...,16.0,13.4,10.5,16.6,22.3,19.2,24.9,19.7,15.8,24.6
4,2018,23809,11.45,5.0,13.0,18.1,14.2,29.3,19.1,19.4,...,15.2,15.0,11.6,18.7,26.0,23.1,28.5,24.3,19.3,30.7
5,2017,23244,11.18,5.1,15.3,20.4,12.0,29.8,18.4,19.4,...,15.1,16.8,13.4,20.5,29.1,26.4,31.4,28.5,23.7,34.8
6,2016,22755,10.94,5.6,15.2,20.8,13.2,28.4,18.8,18.9,...,14.9,17.3,14.0,20.8,28.8,25.1,32.0,29.2,24.7,35.1
7,2015,22464,10.80,6.7,16.3,23.0,13.0,27.1,18.7,18.2,...,14.2,18.9,15.2,22.9,31.8,28.3,34.8,33.5,29.1,39.2
8,2014,22422,10.78,8.2,16.2,24.4,12.3,27.7,18.7,16.9,...,13.2,20.2,16.0,24.6,32.4,30.2,34.3,36.2,31.7,42.1
9,2013,22048,10.60,6.4,18.6,25.0,12.2,27.5,18.0,17.3,...,13.2,20.8,16.9,24.9,31.9,29.0,34.4,38.2,34.8,42.7
10,2012,21715,10.44,6.9,18.0,24.9,12.9,26.7,18.8,16.7,...,12.5,20.8,16.6,25.4,31.0,28.2,33.3,38.3,34.1,43.7
11,2011,21278,10.23,6.7,18.1,24.8,11.6,28.4,18.3,16.8,...,12.9,20.9,17.1,24.9,31.6,29.2,33.6,38.3,35.5,42.3
12,2010,20634,9.92,5.6,14.9,20.5,14.8,27.5,19.6,17.6,...,13.6,17.5,13.6,21.6,25.0,22.1,27.4,31.7,27.4,37.6
13,2009,20293,9.76,6.3,14.2,20.4,14.6,27.8,19.7,17.5,...,13.0,17.5,13.5,21.7,25.7,22.4,28.3,31.0,26.2,37.7
14,2008,20364,9.79,7.0,14.0,21.0,14.8,28.2,19.2,16.7,...,12.4,18.0,13.5,22.6,27.6,24.1,30.5,31.3,26.4,38.4
15,2007,19614,9.43,7.5,13.7,21.3,13.4,29.0,19.5,16.8,...,12.5,18.1,13.5,23.1,26.3,23.2,28.9,32.7,28.0,39.6
16,2006,19074,9.17,7.1,15.1,22.3,12.9,29.5,19.2,16.1,...,11.8,19.0,14.7,23.7,27.8,24.1,30.8,34.5,29.8,41.5
17,2005,18470,8.88,7.3,13.9,21.2,15.4,27.8,19.8,15.8,...,11.6,18.0,13.6,22.7,27.1,23.3,30.3,33.1,28.8,39.6
18,2004,17867,8.59,6.7,14.6,21.3,13.7,29.0,19.9,16.0,...,11.5,18.3,14.0,22.8,25.9,21.7,29.4,33.7,29.6,39.7
19,2003,17400,8.37,7.1,13.8,20.9,14.1,28.5,20.8,15.6,...,11.0,17.9,13.5,22.6,25.3,20.9,29.0,33.3,29.3,39.1
20,2002,17014,8.18,7.0,14.5,21.5,14.3,28.6,19.7,15.9,...,11.1,18.3,13.8,23.2,26.6,22.5,30.0,34.9,30.3,41.5
21,2001,16744,8.05,7.8,15.0,22.9,14.5,28.1,19.7,14.9,...,10.1,19.5,14.5,24.9,28.8,24.1,32.6,37.5,33.7,43.1
22,2000,16286,7.83,7.2,14.8,22.1,13.7,30.4,19.1,14.7,...,9.9,19.0,13.8,24.5,26.7,22.7,30.1,36.4,31.9,43.1
23,1999,15749,7.57,7.5,16.5,23.9,12.7,30.4,18.6,14.3,...,9.6,20.7,15.3,26.7,30.0,24.3,34.7,38.9,33.9,45.8
24,1998,15413,7.41,9.3,15.3,24.5,14.3,28.0,19.9,13.2,...,8.7,21.4,15.8,27.4,31.3,25.7,36.0,38.9,34.2,45.8
25,1997,15214,7.31,10.8,16.3,27.2,14.0,27.9,18.5,12.5,...,8.1,23.6,17.5,30.2,35.4,30.3,39.7,43.5,39.3,50.0
26,1996,14893,7.16,12.9,15.6,28.5,12.3,28.6,18.7,11.9,...,7.6,25.0,18.8,31.7,37.9,33.5,41.8,44.8,41.4,49.8
27,1995,14500,6.97,13.1,13.6,26.6,14.9,27.8,18.9,11.8,...,7.5,23.6,17.3,30.6,33.6,28.8,38.0,42.6,39.1,47.8
28,1994,14167,6.81,14.3,13.3,27.6,14.6,27.3,18.9,11.6,...,7.4,24.7,18.7,31.2,35.9,31.1,40.3,42.7,39.3,47.8
29,1993,13874,6.67,14.8,13.3,28.1,13.5,28.5,19.6,10.4,...,6.3,25.2,19.3,31.7,36.1,32.9,39.1,42.9,39.7,47.5
30,1992,13536,6.51,11.4,17.5,28.9,13.3,28.7,17.8,11.3,...,6.7,25.9,19.7,32.7,37.4,33.8,40.7,43.7,40.9,47.9
31,1991,13208,6.35,12.2,16.0,28.2,12.2,30.2,18.4,11.0,...,6.1,25.4,18.6,32.7,36.6,32.6,40.3,43.4,40.0,48.7
32,1990,12740,6.12,13.0,15.4,28.4,13.2,28.6,19.1,10.8,...,5.6,25.5,18.5,33.4,37.0,32.0,41.5,42.8,39.2,48.2
33,1989,12143,5.84,13.1,14.0,27.1,13.5,28.9,19.9,10.6,...,5.2,24.7,17.4,32.8,35.7,30.5,40.7,39.7,35.4,46.0
34,1988,11629,5.59,13.3,14.3,27.6,11.4,30.4,19.2,11.4,...,5.3,25.4,17.9,33.9,35.8,29.9,41.5,39.1,33.8,46.9
35,1987,11223,5.40,14.8,12.8,27.6,12.4,29.2,20.0,10.8,...,4.7,25.3,17.6,34.2,36.4,30.5,42.1,38.7,33.7,46.1
36,1986,10858,5.22,12.7,15.6,28.3,12.9,28.4,19.9,10.4,...,4.1,26.2,18.3,35.4,37.0,31.1,42.7,39.4,33.9,47.7
37,1985,10670,5.13,13.4,16.4,29.8,12.3,29.2,19.2,9.5,...,3.5,27.7,19.1,37.8,39.4,33.6,44.9,40.3,34.8,48.8
38,1984,10317,4.96,13.1,13.4,26.5,15.6,27.5,20.4,10.1,...,3.6,24.7,16.4,34.7,35.0,28.0,41.8,35.9,29.2,45.1
39,1983,9901,4.76,13.0,15.1,28.1,13.2,29.3,19.9,9.4,...,3.1,26.5,17.8,36.8,36.7,30.7,42.8,37.4,30.2,47.7
40,1982,9499,4.57,10.6,17.6,28.3,13.5,29.4,19.7,9.1,...,2.8,26.6,17.3,37.8,36.9,29.3,44.4,37.5,30.6,47.7
41,1981,8956,4.31,5.3,22.5,27.8,14.4,29.1,20.5,8.2,...,2.4,26.2,16.4,38.4,35.7,26.8,44.7,37.1,29.1,49.4
42,1980,8181,3.93,4.6,21.1,25.7,13.8,31.8,19.9,8.8,...,2.4,24.2,14.4,36.5,34.1,25.3,43.0,33.6,25.3,46.5
43,1979,7360,3.54,5.1,20.7,25.8,13.6,31.1,20.7,8.9,...,2.4,24.3,14.3,37.3,33.7,25.1,42.9,34.6,25.1,49.6
44,1978,6718,3.23,5.4,20.6,26.0,15.4,29.6,19.9,9.1,...,2.3,24.5,14.7,37.5,35.5,25.2,46.0,32.6,23.8,46.5
45,1977,6284,3.02,6.2,20.7,26.9,13.6,30.3,20.5,8.7,...,2.4,25.4,15.5,38.7,36.7,28.0,45.7,36.0,25.6,52.8
46,1976,5914,2.84,7.1,18.0,25.1,15.2,31.2,19.6,9.0,...,2.8,23.6,14.1,36.7,34.8,23.8,46.2,34.8,27.2,46.3
47,1975,5595,2.69,10.2,15.7,25.9,13.9,32.0,19.5,8.7,...,2.5,24.2,14.4,38.2,36.7,25.1,49.1,35.0,27.3,47.5
48,1974,5158,2.48,7.5,16.8,24.3,15.2,31.0,20.6,8.9,...,2.3,22.7,12.8,37.0,34.6,22.8,47.4,33.7,24.5,49.7
49,1973,4701,2.26,9.3,16.3,25.6,12.7,32.9,19.8,9.0,...,2.4,23.8,13.7,38.5,37.3,25.3,50.6,34.9,27.1,48.2

In [ ]:
# Checking for NaN values

df4.isna().sum()

year                                        0
annual_poverty-level_wage                   0
hourly_poverty-level_wage                   0
0-75%_of_poverty_wages                      0
75-100%_of_poverty_wages                    0
share_below_poverty_wages                   0
100-125%_of_poverty_wages                   0
125-200%_of_poverty_wages                   0
200-300%_of_poverty_wages                   0
300%+_of_poverty_wages                      0
men_0-75%_of_poverty_wages                  0
men_75-100%_of_poverty_wages                0
men_share_below_poverty_wages               0
men_100-125%_of_poverty_wages               0
men_125-200%_of_poverty_wages               0
men_200-300%_of_poverty_wages               0
men_300%+_of_poverty_wages                  0
women_0-75%_of_poverty_wages                0
women_75-100%_of_poverty_wages              0
women_share_below_poverty_wages             0
women_100-125%_of_poverty_wages             0
women_125-200%_of_poverty_wages             0
women_200-300%_of_poverty_wages             0
women_300%+_of_poverty_wages                0
white_share_below_poverty_wages             0
white_men_share_below_poverty_wages         0
white_women_share_below_poverty_wages       0
black_share_below_poverty_wages             0
black_men_share_below_poverty_wages         0
black_women_share_below_poverty_wages       0
hispanic_share_below_poverty_wages          0
hispanic_men_share_below_poverty_wages      0
hispanic_women_share_below_poverty_wages    0
dtype: int64

In [ ]:
# Making an array

arr4 = df4.to_numpy()
arr4

array([[2.0220e+03, 2.7733e+04, 1.3330e+01, ..., 1.5400e+01, 1.2300e+01,
        1.9200e+01],
       [2.0210e+03, 2.5688e+04, 1.2350e+01, ..., 1.6800e+01, 1.4200e+01,
        2.0000e+01],
       [2.0200e+03, 2.4544e+04, 1.1800e+01, ..., 1.4900e+01, 1.2000e+01,
        1.8600e+01],
       ...,
       [1.9750e+03, 5.5950e+03, 2.6900e+00, ..., 3.5000e+01, 2.7300e+01,
        4.7500e+01],
       [1.9740e+03, 5.1580e+03, 2.4800e+00, ..., 3.3700e+01, 2.4500e+01,
        4.9700e+01],
       [1.9730e+03, 4.7010e+03, 2.2600e+00, ..., 3.4900e+01, 2.7100e+01,
        4.8200e+01]])

In [ ]:
arr4_t = arr4.transpose()
arr4_t

array([[2.0220e+03, 2.0210e+03, 2.0200e+03, ..., 1.9750e+03, 1.9740e+03,
        1.9730e+03],
       [2.7733e+04, 2.5688e+04, 2.4544e+04, ..., 5.5950e+03, 5.1580e+03,
        4.7010e+03],
       [1.3330e+01, 1.2350e+01, 1.1800e+01, ..., 2.6900e+00, 2.4800e+00,
        2.2600e+00],
       ...,
       [1.5400e+01, 1.6800e+01, 1.4900e+01, ..., 3.5000e+01, 3.3700e+01,
        3.4900e+01],
       [1.2300e+01, 1.4200e+01, 1.2000e+01, ..., 2.7300e+01, 2.4500e+01,
        2.7100e+01],
       [1.9200e+01, 2.0000e+01, 1.8600e+01, ..., 4.7500e+01, 4.9700e+01,
        4.8200e+01]])

In [ ]:
product4 = matmul(arr4, arr4_t)
product4

array([[7.73216897e+08, 7.16500953e+08, 6.84772351e+08, ...,
        1.59171184e+08, 1.47049659e+08, 1.34373943e+08],
       [7.16500953e+08, 6.63967088e+08, 6.34577954e+08, ...,
        1.47727740e+08, 1.36499885e+08, 1.24758737e+08],
       [6.84772351e+08, 6.34577954e+08, 6.06497593e+08, ...,
        1.41324845e+08, 1.30596922e+08, 1.19378593e+08],
       ...,
       [1.59171184e+08, 1.47727740e+08, 1.41324845e+08, ...,
        3.52244728e+07, 3.27770535e+07, 3.02187843e+07],
       [1.47049659e+08, 1.36499885e+08, 1.30596922e+08, ...,
        3.27770535e+07, 3.05206913e+07, 2.81620499e+07],
       [1.34373943e+08, 1.24758737e+08, 1.19378593e+08, ...,
        3.02187843e+07, 2.81620499e+07, 2.60123518e+07]])

In [ ]:
eigenvalues4, eigenvectors4 = linalg.eig(product4)
print(eigenvalues4)
print(eigenvectors4)

[ 1.40335545e+10+0.00000000e+00j  2.58592892e+07+0.00000000e+00j
  9.01768942e+03+0.00000000e+00j  1.76191974e+03+0.00000000e+00j
  8.77685698e+02+0.00000000e+00j  2.25834612e+02+0.00000000e+00j
  1.50849049e+02+0.00000000e+00j  1.11601359e+02+0.00000000e+00j
  7.86208421e+01+0.00000000e+00j  3.28928276e+01+0.00000000e+00j
  2.23302163e+01+0.00000000e+00j  9.25381251e+00+0.00000000e+00j
  7.42428484e+00+0.00000000e+00j  4.76253737e+00+0.00000000e+00j
  2.57436116e+00+0.00000000e+00j  2.10417540e+00+0.00000000e+00j
  1.14205186e+00+0.00000000e+00j  6.08566379e-01+0.00000000e+00j
  2.37303832e-01+0.00000000e+00j  1.16338963e-01+0.00000000e+00j
  6.70587215e-02+0.00000000e+00j  5.38519361e-02+0.00000000e+00j
  3.79627646e-02+0.00000000e+00j  3.72540865e-02+0.00000000e+00j
  3.26031581e-02+0.00000000e+00j  2.82507761e-02+0.00000000e+00j
  1.90564355e-02+0.00000000e+00j  1.59949580e-02+0.00000000e+00j
  1.50484790e-02+0.00000000e+00j  1.05740830e-02+0.00000000e+00j
  7.58124846e-03+0.00000000e+00j  5.44387412e-03+0.00000000e+00j
  5.53400036e-05+0.00000000e+00j -8.14082518e-07+0.00000000e+00j
 -4.75230424e-07+1.34492175e-07j -4.75230424e-07-1.34492175e-07j
  5.36876637e-07+0.00000000e+00j -3.28325566e-07+0.00000000e+00j
  4.66804445e-07+0.00000000e+00j -2.14188649e-07+1.87777670e-08j
 -2.14188649e-07-1.87777670e-08j -9.29526441e-08+0.00000000e+00j
 -6.99505512e-08+0.00000000e+00j  4.77520625e-08+0.00000000e+00j
  1.43046785e-07+7.29025592e-08j  1.43046785e-07-7.29025592e-08j
  9.72796847e-08+0.00000000e+00j  1.41319079e-07+0.00000000e+00j
  2.55708614e-07+0.00000000e+00j  2.41735092e-07+0.00000000e+00j]
[[ 0.23455014+0.j -0.21337947+0.j  0.27379856+0.j ... -0.03834223+0.j
   0.01326448+0.j  0.0103421 +0.j]
 [ 0.21739445+0.j -0.16867012+0.j  0.28023565+0.j ...  0.00595898+0.j
  -0.0237796 +0.j -0.03791447+0.j]
 [ 0.20779675+0.j -0.14380201+0.j  0.34273358+0.j ... -0.05969427+0.j
  -0.04728093+0.j  0.09143133+0.j]
 ...
 [ 0.04879989+0.j  0.26415092+0.j  0.13557287+0.j ...  0.07776326+0.j
  -0.18594225+0.j  0.06690558+0.j]
 [ 0.04513292+0.j  0.27349174+0.j  0.20481763+0.j ... -0.01608652+0.j
   0.12546262+0.j  0.18298678+0.j]
 [ 0.04129858+0.j  0.28339451+0.j  0.15713479+0.j ... -0.01169259+0.j
   0.05283156+0.j -0.17095453+0.j]]

In [ ]:
# Remove the eigenvector with lowest eigenvalue

eigenvectors4 = delete(eigenvectors4, argmin(eigenvalues4), axis = 1)

In [ ]:
print(arr4.shape)
print(eigenvectors4.shape)

(50, 33)
(50, 49)

In [ ]:
arr4 = insert(arr4, [33], zeros((50, 17)), axis = 1)

In [ ]:
# Multiplication now possible!

print(arr4.shape)
print(eigenvectors4.shape)

(50, 50)
(50, 49)

In [ ]:
PCA4 = matmul(arr4, eigenvectors4)
PCA4

array([[ 6577.97228237+0.j, -5114.69547424+0.j,  8301.10641118+0.j, ...,
           99.35797406+0.j,  -646.18743323+0.j, -1033.41823922+0.j],
       [ 6134.54455813+0.j, -4768.56199026+0.j,  7725.42900255+0.j, ...,
           86.76624739+0.j,  -597.38708192+0.j,  -955.81986327+0.j],
       [ 5884.10145127+0.j, -4575.6268269 +0.j,  7404.93791937+0.j, ...,
           80.7678877 +0.j,  -570.49911808+0.j,  -911.73070297+0.j],
       ...,
       [ 1780.52713688+0.j, -1358.69130462+0.j,  2057.64516919+0.j, ...,
          -26.34099737+0.j,  -119.154363  +0.j,  -202.44461299+0.j],
       [ 1682.88389373+0.j, -1285.14040408+0.j,  1936.68730925+0.j, ...,
          -27.37289251+0.j,  -109.98252788+0.j,  -186.10893296+0.j],
       [ 1585.73369268+0.j, -1207.08556962+0.j,  1805.72667666+0.j, ...,
          -30.1559833 +0.j,   -98.75958326+0.j,  -168.84694999+0.j]])

In [ ]:
U4, S4, V4 = linalg.svd(arr4, full_matrices = True)

In [ ]:
U4.shape, V4.shape, S4.shape

((50, 50), (50, 50), (50,))

In [ ]:
print(U4)
print(V4)
print(S4)

[[-0.23455014 -0.21337947 -0.27379856 ... -0.03356218 -0.11617725
   0.00440558]
 [-0.21739445 -0.16867012 -0.28023565 ...  0.13168349  0.13431198
   0.24133104]
 [-0.20779675 -0.14380201 -0.34273358 ...  0.03394529  0.05846595
  -0.10593734]
 ...
 [-0.04879989  0.26415092 -0.13557287 ...  0.34235556 -0.10147255
  -0.15440883]
 [-0.04513292  0.27349174 -0.20481763 ... -0.13400152  0.26689413
  -0.15240876]
 [-0.04129858  0.28339451 -0.15713479 ... -0.15999263 -0.21565472
   0.34095911]]
[[-1.11397379e-01 -9.93752523e-01 -4.77771969e-04 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 9.90358368e-01 -1.11559692e-01 -5.36220861e-05 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-5.58336598e-02  2.07446975e-03  6.89799531e-06 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 ...
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  1.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  1.00000000e+00]]
[1.18463304e+05 5.08520297e+03 9.49615155e+01 4.19752276e+01
 2.96257607e+01 1.50277947e+01 1.22820621e+01 1.05641545e+01
 8.86683946e+00 5.73522690e+00 4.72548588e+00 3.04200800e+00
 2.72475409e+00 2.18232384e+00 1.60448159e+00 1.45057762e+00
 1.06866820e+00 7.80106681e-01 4.87138363e-01 3.41084999e-01
 2.58957147e-01 2.32059872e-01 1.94840304e-01 1.93013227e-01
 1.80563130e-01 1.68080455e-01 1.38044853e-01 1.26471063e-01
 1.22672443e-01 1.02830710e-01 8.70704694e-02 7.37823684e-02
 7.44424769e-03 1.09699756e-11 1.09699756e-11 1.09699756e-11
 1.09699756e-11 1.09699756e-11 1.09699756e-11 1.09699756e-11
 1.09699756e-11 1.09699756e-11 1.09699756e-11 1.09699756e-11
 1.09699756e-11 1.09699756e-11 1.09699756e-11 1.09699756e-11
 1.09699756e-11 1.09699756e-11]

## DataSet 5 – USA Unemployment

Link: https://www.kaggle.com/datasets/asaniczka/unemployment-rates-by-demographics-1978-2023

In [ ]:
# Reading the data into a dataframe

df5 = pd.read_csv("unemployment.csv")
df5

,date,all,16-24,25-54,55-64,65+,less_than_hs,high_school,some_college,bachelor's_degree,...,white_men_16-24,white_men_25-54,white_men_55-64,white_men_65+,white_men_less_than_hs,white_men_high_school,white_men_some_college,white_men_bachelor's_degree,white_men_advanced_degree,population_over_16
0,2023-07-01,3.6,7.8,3.1,2.4,2.7,7.0,4.8,3.4,2.4,...,7.0,2.5,2.1,2.4,7.0,3.8,2.8,2.1,1.6,267002000
1,2023-06-01,3.6,7.8,3.1,2.4,2.8,7.1,4.8,3.4,2.4,...,7.0,2.5,2.1,2.5,7.0,3.8,2.9,2.1,1.6,266801000
2,2023-05-01,3.6,7.9,3.0,2.4,2.8,7.1,4.8,3.4,2.4,...,7.0,2.5,2.1,2.5,6.9,3.8,2.9,2.1,1.6,266618000
3,2023-04-01,3.6,7.9,3.0,2.4,2.8,7.1,4.8,3.4,2.4,...,7.0,2.5,2.2,2.5,6.9,3.8,2.9,2.1,1.6,266443000
4,2023-03-01,3.6,8.0,3.0,2.5,2.8,7.1,4.8,3.5,2.4,...,7.1,2.5,2.2,2.5,6.8,3.9,2.9,2.1,1.7,266272000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
531,1979-04-01,5.9,11.9,4.2,2.8,3.7,9.9,5.4,4.9,3.0,...,9.4,2.8,2.3,3.5,7.5,3.8,3.6,2.0,1.3,164162000
532,1979-03-01,6.0,12.0,4.3,2.8,3.8,9.9,5.4,4.9,3.0,...,9.4,2.8,2.4,3.5,7.5,3.8,3.6,2.1,1.3,164027000
533,1979-02-01,6.0,12.2,4.3,2.8,3.8,9.9,5.4,5.0,3.0,...,9.6,2.8,2.4,3.5,7.6,3.9,3.6,2.1,1.4,163726000
534,1979-01-01,6.1,12.3,4.3,2.9,3.7,10.0,5.5,5.0,3.1,...,9.7,2.9,2.5,3.5,7.6,3.9,3.7,2.1,1.4,163516000
535,1978-12-01,6.1,12.4,4.3,2.9,3.8,10.0,5.5,5.0,3.1,...,9.7,2.9,2.5,3.6,7.6,4.0,3.7,2.1,1.4,163272000

In [ ]:
# dropping non-numeric column

df5.drop(columns = ["date"], inplace = True)
df5

,all,16-24,25-54,55-64,65+,less_than_hs,high_school,some_college,bachelor's_degree,advanced_degree,...,white_men_16-24,white_men_25-54,white_men_55-64,white_men_65+,white_men_less_than_hs,white_men_high_school,white_men_some_college,white_men_bachelor's_degree,white_men_advanced_degree,population_over_16
0,3.6,7.8,3.1,2.4,2.7,7.0,4.8,3.4,2.4,1.7,...,7.0,2.5,2.1,2.4,7.0,3.8,2.8,2.1,1.6,267002000
1,3.6,7.8,3.1,2.4,2.8,7.1,4.8,3.4,2.4,1.7,...,7.0,2.5,2.1,2.5,7.0,3.8,2.9,2.1,1.6,266801000
2,3.6,7.9,3.0,2.4,2.8,7.1,4.8,3.4,2.4,1.7,...,7.0,2.5,2.1,2.5,6.9,3.8,2.9,2.1,1.6,266618000
3,3.6,7.9,3.0,2.4,2.8,7.1,4.8,3.4,2.4,1.7,...,7.0,2.5,2.2,2.5,6.9,3.8,2.9,2.1,1.6,266443000
4,3.6,8.0,3.0,2.5,2.8,7.1,4.8,3.5,2.4,1.7,...,7.1,2.5,2.2,2.5,6.8,3.9,2.9,2.1,1.7,266272000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
531,5.9,11.9,4.2,2.8,3.7,9.9,5.4,4.9,3.0,2.0,...,9.4,2.8,2.3,3.5,7.5,3.8,3.6,2.0,1.3,164162000
532,6.0,12.0,4.3,2.8,3.8,9.9,5.4,4.9,3.0,2.0,...,9.4,2.8,2.4,3.5,7.5,3.8,3.6,2.1,1.3,164027000
533,6.0,12.2,4.3,2.8,3.8,9.9,5.4,5.0,3.0,2.0,...,9.6,2.8,2.4,3.5,7.6,3.9,3.6,2.1,1.4,163726000
534,6.1,12.3,4.3,2.9,3.7,10.0,5.5,5.0,3.1,2.0,...,9.7,2.9,2.5,3.5,7.6,3.9,3.7,2.1,1.4,163516000
535,6.1,12.4,4.3,2.9,3.8,10.0,5.5,5.0,3.1,2.0,...,9.7,2.9,2.5,3.6,7.6,4.0,3.7,2.1,1.4,163272000

In [ ]:
# Checking for NaN values

df5.isna().sum()

all                            0
16-24                          0
25-54                          0
55-64                          0
65+                            0
                              ..
white_men_high_school          0
white_men_some_college         0
white_men_bachelor's_degree    0
white_men_advanced_degree      0
population_over_16             0
Length: 121, dtype: int64

In [ ]:
# Making an array

arr5 = df5.to_numpy()
arr5

array([[3.60000e+00, 7.80000e+00, 3.10000e+00, ..., 2.10000e+00,
        1.60000e+00, 2.67002e+08],
       [3.60000e+00, 7.80000e+00, 3.10000e+00, ..., 2.10000e+00,
        1.60000e+00, 2.66801e+08],
       [3.60000e+00, 7.90000e+00, 3.00000e+00, ..., 2.10000e+00,
        1.60000e+00, 2.66618e+08],
       ...,
       [6.00000e+00, 1.22000e+01, 4.30000e+00, ..., 2.10000e+00,
        1.40000e+00, 1.63726e+08],
       [6.10000e+00, 1.23000e+01, 4.30000e+00, ..., 2.10000e+00,
        1.40000e+00, 1.63516e+08],
       [6.10000e+00, 1.24000e+01, 4.30000e+00, ..., 2.10000e+00,
        1.40000e+00, 1.63272e+08]])

In [ ]:
arr5_t = arr5.transpose()
arr5_t

array([[3.60000e+00, 3.60000e+00, 3.60000e+00, ..., 6.00000e+00,
        6.10000e+00, 6.10000e+00],
       [7.80000e+00, 7.80000e+00, 7.90000e+00, ..., 1.22000e+01,
        1.23000e+01, 1.24000e+01],
       [3.10000e+00, 3.10000e+00, 3.00000e+00, ..., 4.30000e+00,
        4.30000e+00, 4.30000e+00],
       ...,
       [2.10000e+00, 2.10000e+00, 2.10000e+00, ..., 2.10000e+00,
        2.10000e+00, 2.10000e+00],
       [1.60000e+00, 1.60000e+00, 1.60000e+00, ..., 1.40000e+00,
        1.40000e+00, 1.40000e+00],
       [2.67002e+08, 2.66801e+08, 2.66618e+08, ..., 1.63726e+08,
        1.63516e+08, 1.63272e+08]])

In [ ]:
product5 = matmul(arr5, arr5_t)
product5

array([[7.12900680e+16, 7.12364006e+16, 7.11875392e+16, ...,
        4.37151695e+16, 4.36590990e+16, 4.35939505e+16],
       [7.12364006e+16, 7.11827736e+16, 7.11339490e+16, ...,
        4.36822605e+16, 4.36262323e+16, 4.35611329e+16],
       [7.11875392e+16, 7.11339490e+16, 7.10851579e+16, ...,
        4.36522987e+16, 4.35963089e+16, 4.35312541e+16],
       ...,
       [4.37151695e+16, 4.36822605e+16, 4.36522987e+16, ...,
        2.68062031e+16, 2.67718206e+16, 2.67318715e+16],
       [4.36590990e+16, 4.36262323e+16, 4.35963089e+16, ...,
        2.67718206e+16, 2.67374823e+16, 2.66975844e+16],
       [4.35939505e+16, 4.35611329e+16, 4.35312541e+16, ...,
        2.67318715e+16, 2.66975844e+16, 2.66577460e+16]])

In [ ]:
eigenvalues5, eigenvectors5 = linalg.eig(product5)
print(eigenvalues5)
print(eigenvectors5)

[ 2.53168648e+19   +0.j          4.70732971e+05   +0.j
  2.58393920e+04   +0.j          9.80810963e+03   +0.j
  7.79454737e+03   +0.j          3.89398683e+03   +0.j
  2.31296230e+03   +0.j          1.79086176e+03   +0.j
  1.60565565e+03  +49.91848854j  1.60565565e+03  -49.91848854j
 -1.41058717e+03   +0.j         -1.38072463e+03   +0.j
  9.56865409e+02 +743.65289182j  9.56865409e+02 -743.65289182j
  3.29548254e+02+1170.25566606j  3.29548254e+02-1170.25566606j
  5.63398597e+02+1059.62614697j  5.63398597e+02-1059.62614697j
 -1.02409561e+03 +724.2216877j  -1.02409561e+03 -724.2216877j
 -6.84411186e+02+1001.00880737j -6.84411186e+02-1001.00880737j
  1.10694249e+03 +207.16910801j  1.10694249e+03 -207.16910801j
  4.88495772e+01+1100.56887175j  4.88495772e+01-1100.56887175j
 -9.99741946e+02 +437.72238744j -9.99741946e+02 -437.72238744j
 -3.46147203e+02+1013.19694925j -3.46147203e+02-1013.19694925j
  9.82605575e+02   +0.j          2.10888894e+02 +756.13950679j
  2.10888894e+02 -756.13950679j  8.16995284e+02   +0.j
 -7.06513098e+02   +0.j          7.11381259e+02  +54.1966186j
  7.11381259e+02  -54.1966186j   5.75734923e+02   +0.j
  5.11266241e+02   +0.j          4.39433505e+02  +24.79623349j
  4.39433505e+02  -24.79623349j  1.48180655e+01 +361.12354304j
  1.48180655e+01 -361.12354304j -3.22719863e+02  +98.97435451j
 -3.22719863e+02  -98.97435451j  3.60062264e+02  +16.68804759j
  3.60062264e+02  -16.68804759j  3.20045516e+02  +93.64369305j
  3.20045516e+02  -93.64369305j  2.54963729e+02 +191.76080507j
  2.54963729e+02 -191.76080507j  2.76382144e+02 +155.06253964j
  2.76382144e+02 -155.06253964j -2.97909466e+02   +0.j
  3.12721141e+02   +0.j          2.85862614e+02   +0.j
 -1.81304189e+02 +162.07063768j -1.81304189e+02 -162.07063768j
 -2.39313345e+02   +0.j         -2.15874165e+02  +94.89695078j
 -2.15874165e+02  -94.89695078j -1.87667145e+02 +143.25954664j
 -1.87667145e+02 -143.25954664j  2.18249830e+02 +128.89921132j
  2.18249830e+02 -128.89921132j -2.32171767e+02  +25.16676578j
 -2.32171767e+02  -25.16676578j -1.52417392e+02 +177.2191613j
 -1.52417392e+02 -177.2191613j   9.01691764e+01 +222.1656287j
  9.01691764e+01 -222.1656287j   2.52909171e+02  +55.5441973j
  2.52909171e+02  -55.5441973j   2.58691327e+02   +4.5310201j
  2.58691327e+02   -4.5310201j   1.76994179e+02 +156.0093251j
  1.76994179e+02 -156.0093251j  -1.64795007e+01 +216.75823059j
 -1.64795007e+01 -216.75823059j -4.63228474e+01 +207.00978166j
 -4.63228474e+01 -207.00978166j  1.47531413e+02 +173.24457208j
  1.47531413e+02 -173.24457208j -6.47095561e+01 +196.68548752j
 -6.47095561e+01 -196.68548752j -1.98708463e+02   +0.j
  5.54157319e+01 +206.36566235j  5.54157319e+01 -206.36566235j
 -1.93759112e+02  +70.18516883j -1.93759112e+02  -70.18516883j
 -1.98241311e+02  +45.61361655j -1.98241311e+02  -45.61361655j
  6.84025330e+01 +202.51471809j  6.84025330e+01 -202.51471809j
 -1.88814713e+02  +67.25694526j -1.88814713e+02  -67.25694526j
 -1.68449388e+02 +111.5678718j  -1.68449388e+02 -111.5678718j
  1.03735484e+02 +185.42659053j  1.03735484e+02 -185.42659053j
 -1.00111898e+02 +174.49072671j -1.00111898e+02 -174.49072671j
  2.05378907e+02  +96.16056871j  2.05378907e+02  -96.16056871j
  2.28646841e+02  +21.1123444j   2.28646841e+02  -21.1123444j
 -1.01150489e+02 +169.15306532j -1.01150489e+02 -169.15306532j
 -1.31524908e+02 +148.83413687j -1.31524908e+02 -148.83413687j
  2.10065228e+02  +81.45506438j  2.10065228e+02  -81.45506438j
  1.60343328e+02 +140.60501871j  1.60343328e+02 -140.60501871j
  2.14430637e+02   +3.37318985j  2.14430637e+02   -3.37318985j
  6.73933750e+01 +184.25487138j  6.73933750e+01 -184.25487138j
  2.09405939e+02  +38.47527474j  2.09405939e+02  -38.47527474j
 -1.40176127e+02 +134.54624143j -1.40176127e+02 -134.54624143j
  1.92328772e+02  +80.19348725j  1.92328772e+02  -80.19348725j
  1.20290062e+02 +158.18610694j  1.20290062e+02 -158.18610694j
  1.63579330e+02 +119.2906999j   1.63579330e+02 -119.2906999j
  1.74531720e-01 +190.13846056j  1.74531720e-01 -190.13846056j
  1.97091311e+02  +33.73559606j  1.97091311e+02  -33.73559606j
  1.51201297e+02 +120.502708j    1.51201297e+02 -120.502708j
  1.80427267e+02  +61.86950529j  1.80427267e+02  -61.86950529j
  1.74297369e+02  +72.29983688j  1.74297369e+02  -72.29983688j
  3.28208087e+01 +179.20033292j  3.28208087e+01 -179.20033292j
 -7.28936244e+00 +180.56972127j -7.28936244e+00 -180.56972127j
  1.18171969e+02 +137.31024517j  1.18171969e+02 -137.31024517j
 -1.52160254e+02 +112.24033847j -1.52160254e+02 -112.24033847j
 -5.27404069e+01 +173.57309328j -5.27404069e+01 -173.57309328j
 -1.04208083e+02 +150.26261233j -1.04208083e+02 -150.26261233j
 -1.68643717e+02  +77.20238526j -1.68643717e+02  -77.20238526j
 -1.36204946e+02 +116.42648302j -1.36204946e+02 -116.42648302j
 -4.38626198e+01 +170.61255552j -4.38626198e+01 -170.61255552j
 -1.82326894e+02   +3.49191583j -1.82326894e+02   -3.49191583j
 -1.10712198e+02 +134.98672118j -1.10712198e+02 -134.98672118j
  7.91880708e+01 +153.26553173j  7.91880708e+01 -153.26553173j
 -1.76206253e+02  +23.62666704j -1.76206253e+02  -23.62666704j
 -1.58381746e+02  +75.06509688j -1.58381746e+02  -75.06509688j
  1.76554152e+02  +41.76576528j  1.76554152e+02  -41.76576528j
  1.49384132e+02  +94.56130175j  1.49384132e+02  -94.56130175j
  1.52169604e+02  +86.86350283j  1.52169604e+02  -86.86350283j
  4.28477340e+01 +165.00089716j  4.28477340e+01 -165.00089716j
 -1.15089755e+02 +124.73458385j -1.15089755e+02 -124.73458385j
 -1.71199677e+02  +35.62589291j -1.71199677e+02  -35.62589291j
 -6.97009099e+01 +152.01623335j -6.97009099e+01 -152.01623335j
  8.00781570e+00 +162.88240942j  8.00781570e+00 -162.88240942j
  1.61141449e+02  +68.61814644j  1.61141449e+02  -68.61814644j
 -1.41647104e+01 +160.8700309j  -1.41647104e+01 -160.8700309j
 -1.29980425e+02  +99.84248286j -1.29980425e+02  -99.84248286j
 -1.55752492e+02  +58.23740577j -1.55752492e+02  -58.23740577j
 -1.65200932e+02   +0.j         -4.67831604e+01 +154.01468504j
 -4.67831604e+01 -154.01468504j  8.54637038e+01 +137.63632468j
  8.54637038e+01 -137.63632468j  1.74775261e+02   +7.44417087j
  1.74775261e+02   -7.44417087j  1.65430515e+02  +10.32156799j
  1.65430515e+02  -10.32156799j  1.31563351e+02  +97.04119999j
  1.31563351e+02  -97.04119999j  6.04629577e+01 +142.02787381j
  6.04629577e+01 -142.02787381j -1.49869772e+02  +50.36594425j
 -1.49869772e+02  -50.36594425j  9.59442445e+01 +124.32856345j
  9.59442445e+01 -124.32856345j  2.44573188e+00 +148.64648682j
  2.44573188e+00 -148.64648682j -1.10026937e+02 +108.20004084j
 -1.10026937e+02 -108.20004084j -8.04694545e+01 +126.03838161j
 -8.04694545e+01 -126.03838161j -1.52498713e+02  +32.22812437j
 -1.52498713e+02  -32.22812437j -1.32143958e+02  +71.9250742j
 -1.32143958e+02  -71.9250742j   1.14495516e+02  +99.81137252j
  1.14495516e+02  -99.81137252j -1.02433160e+02 +106.19175528j
 -1.02433160e+02 -106.19175528j  7.78752130e+01 +127.14855206j
  7.78752130e+01 -127.14855206j  1.22077302e+02  +90.46626729j
  1.22077302e+02  -90.46626729j  3.47597311e+01 +141.96887432j
  3.47597311e+01 -141.96887432j  1.35621620e+02  +67.17558106j
  1.35621620e+02  -67.17558106j  1.54196087e+02  +28.10404643j
  1.54196087e+02  -28.10404643j  1.48455890e+02  +41.0906992j
  1.48455890e+02  -41.0906992j  -4.98120848e+01 +135.06404792j
 -4.98120848e+01 -135.06404792j  1.52423566e+02  +24.11339677j
  1.52423566e+02  -24.11339677j  8.88494653e+01 +111.76170742j
  8.88494653e+01 -111.76170742j -7.70146353e+01 +115.67018077j
 -7.70146353e+01 -115.67018077j -1.48209547e+02   +7.59675363j
 -1.48209547e+02   -7.59675363j -1.22021941e+02  +71.63418653j
 -1.22021941e+02  -71.63418653j -1.40591095e+02  +40.32186623j
 -1.40591095e+02  -40.32186623j -1.04112342e+02  +87.87890889j
 -1.04112342e+02  -87.87890889j  1.09664558e+02  +84.67155714j
  1.09664558e+02  -84.67155714j  6.80965859e+01 +123.3227826j
  6.80965859e+01 -123.3227826j  -3.17346383e+01 +135.38567222j
 -3.17346383e+01 -135.38567222j  4.23584955e+01 +130.34758052j
  4.23584955e+01 -130.34758052j -1.41708773e+02   +0.j
  2.51352546e+01 +133.58801852j  2.51352546e+01 -133.58801852j
  1.24393164e+02  +65.10148727j  1.24393164e+02  -65.10148727j
 -3.49656263e+01 +128.51852168j -3.49656263e+01 -128.51852168j
  1.42049793e+02   +0.j          1.35715264e+02  +39.42322595j
  1.35715264e+02  -39.42322595j  9.54895823e+00 +130.27206754j
  9.54895823e+00 -130.27206754j -1.30630851e+02  +44.77138638j
 -1.30630851e+02  -44.77138638j  8.86789200e+01  +97.3603606j
  8.86789200e+01  -97.3603606j  -8.90800091e+01  +96.33735041j
 -8.90800091e+01  -96.33735041j -1.20406257e+02  +58.72648942j
 -1.20406257e+02  -58.72648942j  7.31815300e+01 +104.87172389j
  7.31815300e+01 -104.87172389j  1.07677377e+02  +74.85040403j
  1.07677377e+02  -74.85040403j -5.09717310e+01 +117.36069972j
 -5.09717310e+01 -117.36069972j -1.25024163e+02  +40.88038482j
 -1.25024163e+02  -40.88038482j -9.79666724e+01  +82.28349853j
 -9.79666724e+01  -82.28349853j -5.63275257e+01 +107.71902967j
 -5.63275257e+01 -107.71902967j -1.24921773e+02  +21.60941127j
 -1.24921773e+02  -21.60941127j  1.28684555e+02  +19.15043398j
  1.28684555e+02  -19.15043398j  1.23589255e+02  +33.02826787j
  1.23589255e+02  -33.02826787j -6.32932686e+00 +121.2568588j
 -6.32932686e+00 -121.2568588j   3.84985386e+01 +112.96487073j
  3.84985386e+01 -112.96487073j -7.96592004e+01  +88.58318414j
 -7.96592004e+01  -88.58318414j  8.29655189e+01  +88.10223851j
  8.29655189e+01  -88.10223851j  8.97555666e+00 +118.03939847j
  8.97555666e+00 -118.03939847j  1.00906385e+02  +67.62285245j
  1.00906385e+02  -67.62285245j -6.80953661e+01  +94.58975407j
 -6.80953661e+01  -94.58975407j  3.73994085e+01 +108.15203889j
  3.73994085e+01 -108.15203889j -9.91034183e+01  +56.30866874j
 -9.91034183e+01  -56.30866874j -1.16738394e+02   +8.6767573j
 -1.16738394e+02   -8.6767573j   1.11672656e+02  +47.02631374j
  1.11672656e+02  -47.02631374j -1.10914980e+02  +22.57370441j
 -1.10914980e+02  -22.57370441j  1.22084396e+02   +3.89683428j
  1.22084396e+02   -3.89683428j  9.02056129e+01  +72.23185288j
  9.02056129e+01  -72.23185288j -2.45108165e+01 +107.96212781j
 -2.45108165e+01 -107.96212781j  1.20862079e+02  +12.54822692j
  1.20862079e+02  -12.54822692j -7.74930328e+01  +79.46927809j
 -7.74930328e+01  -79.46927809j -8.92549839e+01  +56.12246557j
 -8.92549839e+01  -56.12246557j -1.12523855e+02   +0.j
  4.11383152e+01  +98.66160272j  4.11383152e+01  -98.66160272j
  6.41530824e+01  +89.46264002j  6.41530824e+01  -89.46264002j
 -1.07039639e+02  +28.56540108j -1.07039639e+02  -28.56540108j
 -9.91745182e+01  +32.52529595j -9.91745182e+01  -32.52529595j
  8.86824473e+01  +65.26617414j  8.86824473e+01  -65.26617414j
  1.07477301e+02  +35.05800379j  1.07477301e+02  -35.05800379j
  1.01577272e+02  +44.43086217j  1.01577272e+02  -44.43086217j
  1.09215219e+02  +22.48062072j  1.09215219e+02  -22.48062072j
 -3.86522030e+01  +98.84094966j -3.86522030e+01  -98.84094966j
 -4.49744492e+00 +103.99309475j -4.49744492e+00 -103.99309475j
  5.81764172e+01  +88.95179197j  5.81764172e+01  -88.95179197j
 -3.68380120e+01  +95.47395177j -3.68380120e+01  -95.47395177j
 -5.17239111e+01  +86.02833165j -5.17239111e+01  -86.02833165j
  6.44039776e+01  +77.70906665j  6.44039776e+01  -77.70906665j
  1.36120487e+01 +100.06618411j  1.36120487e+01 -100.06618411j
 -9.33096528e+01  +37.92882488j -9.33096528e+01  -37.92882488j
 -6.96180405e+01  +71.29156069j -6.96180405e+01  -71.29156069j
 -5.08225780e+01  +82.14097641j -5.08225780e+01  -82.14097641j
  4.57115267e+01  +84.83089481j  4.57115267e+01  -84.83089481j
  2.63896051e+01  +95.14078395j  2.63896051e+01  -95.14078395j
 -1.00243277e+02   +2.83855352j -1.00243277e+02   -2.83855352j
  8.20416894e+01  +48.2817857j   8.20416894e+01  -48.2817857j
  6.82510883e+01  +64.13800005j  6.82510883e+01  -64.13800005j
  1.03076650e+02  +11.69901433j  1.03076650e+02  -11.69901433j
 -8.33140109e+00  +93.02715601j -8.33140109e+00  -93.02715601j
 -2.34785208e+01  +90.26996486j -2.34785208e+01  -90.26996486j
 -9.73230251e+01   +0.j         -6.70367310e+01  +62.93021813j
 -6.70367310e+01  -62.93021813j -7.47627006e+01  +53.13968757j
 -7.47627006e+01  -53.13968757j  5.37222686e+01  +76.02201447j
  5.37222686e+01  -76.02201447j  9.60830007e+01   +0.j
 -3.46839103e+01  +83.05298038j -3.46839103e+01  -83.05298038j
 -8.67399552e+01  +15.85569856j -8.67399552e+01  -15.85569856j
 -1.35063209e+00  +87.41209328j -1.35063209e+00  -87.41209328j
  8.84821612e+01  +35.45959193j  8.84821612e+01  -35.45959193j
 -7.51431842e+01  +44.60781285j -7.51431842e+01  -44.60781285j
  4.19369252e+01  +76.88447999j  4.19369252e+01  -76.88447999j
  1.35299014e+01  +85.3816587j   1.35299014e+01  -85.3816587j
  9.17876342e+01   +4.44604681j  9.17876342e+01   -4.44604681j
  7.94091027e+01  +37.9218049j   7.94091027e+01  -37.9218049j
 -4.39522474e+01  +72.49745868j -4.39522474e+01  -72.49745868j
  8.54662320e+01  +20.05288914j  8.54662320e+01  -20.05288914j
  2.86540030e+01  +77.4245074j   2.86540030e+01  -77.4245074j
 -7.89623437e+01  +32.9147663j  -7.89623437e+01  -32.9147663j
  5.54590635e+01  +58.79461371j  5.54590635e+01  -58.79461371j
 -7.12271064e+01  +33.40362519j -7.12271064e+01  -33.40362519j
  7.19270106e+01  +33.45344254j  7.19270106e+01  -33.45344254j
 -3.05267568e+01  +73.84758993j -3.05267568e+01  -73.84758993j
 -2.41042677e+01  +76.33732642j -2.41042677e+01  -76.33732642j
 -7.98338684e+01   +0.j          7.72929990e+01   +0.j
 -7.53751029e+01  +20.30246108j -7.53751029e+01  -20.30246108j
 -1.42377965e-01  +75.26464018j -1.42377965e-01  -75.26464018j
 -4.08818429e+01  +62.28138885j -4.08818429e+01  -62.28138885j
 -6.17328970e+01  +42.49644201j -6.17328970e+01  -42.49644201j
 -7.23918136e+01   +0.j          7.46993881e+01   +7.85668731j
  7.46993881e+01   -7.85668731j  6.00040176e+01  +37.99771062j
  6.00040176e+01  -37.99771062j  1.30115226e+01  +67.86979579j
  1.30115226e+01  -67.86979579j  4.13308231e+01  +53.05844415j
  4.13308231e+01  -53.05844415j  2.74356564e+01  +62.08817157j
  2.74356564e+01  -62.08817157j -6.68033338e+01  +18.50031357j
 -6.68033338e+01  -18.50031357j -5.77126883e+01  +30.03941159j
 -5.77126883e+01  -30.03941159j -4.74487288e+01  +41.86224666j
 -4.74487288e+01  -41.86224666j  5.96030876e+01  +25.12359775j
  5.96030876e+01  -25.12359775j  5.80988026e+01  +26.8772529j
  5.80988026e+01  -26.8772529j   4.44164183e+01  +44.69905521j
  4.44164183e+01  -44.69905521j -3.63683140e+01  +50.09581548j
 -3.63683140e+01  -50.09581548j  2.15999774e+01  +55.99118119j
  2.15999774e+01  -55.99118119j  3.70220636e+01  +43.28906061j
  3.70220636e+01  -43.28906061j  4.67537488e+01  +32.42598297j
  4.67537488e+01  -32.42598297j -2.15248090e+01  +53.79005678j
 -2.15248090e+01  -53.79005678j -5.97863678e+01   +0.j
  5.87225065e+01   +2.63543891j  5.87225065e+01   -2.63543891j
  2.98089609e+00  +59.03565399j  2.98089609e+00  -59.03565399j
 -8.52933870e+00  +56.54105951j -8.52933870e+00  -56.54105951j
  1.15952377e+01  +54.38192918j  1.15952377e+01  -54.38192918j
  4.76581106e+01  +16.97423018j  4.76581106e+01  -16.97423018j
 -5.19628682e+01  +12.30415842j -5.19628682e+01  -12.30415842j
 -3.56239822e+01  +36.86960423j -3.56239822e+01  -36.86960423j
 -4.82972913e+01  +20.18563553j -4.82972913e+01  -20.18563553j
 -2.91000092e+01  +38.62317164j -2.91000092e+01  -38.62317164j
 -9.55219416e+00  +48.17072311j -9.55219416e+00  -48.17072311j
  1.71713325e+01  +43.12202967j  1.71713325e+01  -43.12202967j
  4.56430187e+01   +0.j          4.46481402e+01   +0.j
 -4.36905808e+01  +19.28735651j -4.36905808e+01  -19.28735651j
  2.75800201e+01  +30.34843676j  2.75800201e+01  -30.34843676j
  3.45096196e+01   +0.j         -3.52858637e+00  +43.06000722j
 -3.52858637e+00  -43.06000722j  1.68895422e+01  +36.21402808j
  1.68895422e+01  -36.21402808j -1.53966679e+01  +37.99253871j
 -1.53966679e+01  -37.99253871j -2.58767933e+01  +26.07398421j
 -2.58767933e+01  -26.07398421j -1.39433109e+01  +33.49560298j
 -1.39433109e+01  -33.49560298j  1.60008614e+01  +30.06465628j
  1.60008614e+01  -30.06465628j -3.08515190e+01  +13.30473752j
 -3.08515190e+01  -13.30473752j  1.36361277e+01  +24.1884642j
  1.36361277e+01  -24.1884642j  -3.27202424e+01   +0.j
 -1.51974944e+01  +18.47862774j -1.51974944e+01  -18.47862774j
  1.28622688e+00  +20.1011784j   1.28622688e+00  -20.1011784j
  1.61018167e+00   +0.j         -2.12073432e+01   +3.80601228j
 -2.12073432e+01   -3.80601228j  2.58951497e+01  +11.37711312j
  2.58951497e+01  -11.37711312j  2.79367592e+01   +5.3338895j
  2.79367592e+01   -5.3338895j  -1.44891707e+01   +1.65244427j
 -1.44891707e+01   -1.65244427j -1.25480048e+01   +0.j
  1.74862486e+01  +10.13795405j  1.74862486e+01  -10.13795405j
  1.61235514e+01   +0.j          3.64535981e+00   +0.j        ]
[[-0.05306517+0.j         -0.08788732+0.j          0.02538438+0.j
  ...  0.01104266+0.02243236j  0.02324332+0.j
  -0.01299195+0.j        ]
 [-0.05302522+0.j         -0.08828886+0.j          0.02566306+0.j
  ...  0.00167472+0.00387629j  0.00201758+0.j
   0.00348628+0.j        ]
 [-0.05298885+0.j         -0.087595  +0.j          0.03624558+0.j
  ...  0.00137746+0.00278212j  0.00534461+0.j
   0.00033965+0.j        ]
 ...
 [-0.03253964+0.j          0.03558455+0.j          0.07255286+0.j
  ... -0.02024638+0.01951011j  0.00275286+0.j
   0.01805579+0.j        ]
 [-0.0324979 +0.j          0.03714845+0.j          0.0798878 +0.j
  ... -0.06206747-0.01184392j -0.0056847 +0.j
  -0.08043444+0.j        ]
 [-0.03244941+0.j          0.03897511+0.j          0.08050793+0.j
  ...  0.02958036-0.0010383j   0.0414992 +0.j
   0.00215039+0.j        ]]

In [ ]:
# Remove the eigenvector with lowest eigenvalue

eigenvectors5 = delete(eigenvectors5, argmin(eigenvalues5), axis = 1)

In [ ]:
print(arr5.shape)
print(eigenvectors5.shape)

(536, 121)
(536, 535)

In [ ]:
arr5 = insert(arr5, [121], zeros((536, 415)), axis = 1)

In [ ]:
# Multiplication now possible!

print(arr5.shape)
print(eigenvectors5.shape)

(536, 536)
(536, 535)

In [ ]:
PCA5 = matmul(arr5, eigenvectors5)
PCA5

array([[-13041110.93492279     +0.j        ,
          5505504.09178573     +0.j        ,
        -17171417.78853279     +0.j        , ...,
          4250864.65316167+436492.43057967j,
           170417.94384923     +0.j        ,
        -12924426.34067936     +0.j        ],
       [-13031293.568408       +0.j        ,
          5501359.52241363     +0.j        ,
        -17158491.09598066     +0.j        , ...,
          4247664.61990089+436163.85109252j,
           170289.70045361     +0.j        ,
        -12914696.74792923     +0.j        ],
       [-13022355.32127673     +0.j        ,
          5497586.17093346     +0.j        ,
        -17146721.99434229     +0.j        , ...,
          4244751.14790846+435864.71433986j,
           170173.01712159     +0.j        ,
        -12905838.4762516      +0.j        ],
       ...,
       [ -7996855.3868002      +0.j        ,
          3375955.07278761     +0.j        ,
        -10529546.88453605     +0.j        , ...,
          2606637.23337728+267657.83343415j,
           104501.62483224     +0.j        ,
         -7925276.23347879     +0.j        ],
       [ -7986598.94932861     +0.j        ,
          3371624.38910043     +0.j        ,
        -10516041.53346175     +0.j        , ...,
          2603293.82903655+267314.6428507j ,
           104367.63114663     +0.j        ,
         -7915111.1088268      +0.j        ],
       [ -7974681.86585808     +0.j        ,
          3366592.64486443     +0.j        ,
        -10500349.61424254     +0.j        , ...,
          2599409.06602225+266915.7913799j ,
           104211.77612195     +0.j        ,
         -7903300.12315457     +0.j        ]])

In [ ]:
U5, S5, V5 = linalg.svd(arr5, full_matrices = True)

In [ ]:
U5.shape, V5.shape, S5.shape

((536, 536), (536, 536), (536,))

In [ ]:
print(U5)
print(V5)
print(S5)

[[-0.05306517 -0.08772647  0.02634202 ... -0.02844224 -0.04605823
  -0.04000123]
 [-0.05302522 -0.08773507  0.02543594 ...  0.03747159  0.00302195
   0.05242269]
 [-0.05298885 -0.08788242  0.02571781 ...  0.09648313  0.05715509
   0.04497585]
 ...
 [-0.03253964  0.03577401  0.07769054 ...  0.7145302  -0.17746804
  -0.16133392]
 [-0.0324979   0.03707387  0.07738213 ... -0.16406394  0.66622782
  -0.23810758]
 [-0.03244941  0.03890043  0.07830402 ... -0.1710979  -0.25563269
   0.58437047]]
[[-2.77373101e-08 -5.67527576e-08 -2.30406062e-08 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 6.89716355e-02  1.17748808e-01  5.62582621e-02 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-2.58455851e-02 -1.72617898e-02 -5.68642293e-02 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 ...
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  1.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  1.00000000e+00]]
[5.03158671e+09 6.86194252e+02 1.60721004e+02 9.87928468e+01
 8.84975039e+01 6.32152070e+01 4.80007158e+01 4.35277150e+01
 3.95122319e+01 3.89794983e+01 2.88884890e+01 2.60505276e+01
 2.45004048e+01 2.22176620e+01 1.92242344e+01 1.80518933e+01
 1.76396503e+01 1.66963719e+01 1.64996407e+01 1.59265639e+01
 1.40582547e+01 1.31122666e+01 1.23625045e+01 1.20518867e+01
 1.17974245e+01 1.08674226e+01 1.01341379e+01 9.32953072e+00
 8.33437881e+00 8.24382126e+00 7.89601811e+00 7.30173480e+00
 6.88486522e+00 6.43746609e+00 6.28071762e+00 6.10724494e+00
 5.76889602e+00 5.41560160e+00 5.11193401e+00 4.79231287e+00
 4.30857161e+00 4.20049083e+00 3.83357597e+00 3.46943350e+00
 3.02114271e+00 2.74087110e+00 2.69796376e+00 2.42157312e+00
 2.22861095e+00 1.98632797e+00 1.83023448e+00 1.77887456e+00
 1.61580103e+00 1.44937268e+00 1.37126924e+00 1.32288344e+00
 1.24038459e+00 1.14007502e+00 1.11621638e+00 1.03551386e+00
 1.01468643e+00 9.88807755e-01 9.32224382e-01 8.96498412e-01
 8.70898848e-01 8.57068524e-01 8.41526643e-01 8.28877232e-01
 8.22580269e-01 8.11801967e-01 8.10883534e-01 7.88183626e-01
 7.83716040e-01 7.71583862e-01 7.70495431e-01 7.65961350e-01
 7.58519674e-01 7.50066320e-01 7.38542635e-01 7.29914190e-01
 7.23434811e-01 7.09476396e-01 7.00444119e-01 6.99877164e-01
 6.87001055e-01 6.85594369e-01 6.77963633e-01 6.63103543e-01
 6.61344149e-01 6.51824083e-01 6.48515588e-01 6.38695022e-01
 6.33886109e-01 6.23725416e-01 6.22944398e-01 6.17095256e-01
 6.11022455e-01 6.01770290e-01 5.92791750e-01 5.87753717e-01
 5.83218973e-01 5.79663669e-01 5.69371078e-01 5.64794962e-01
 5.58229417e-01 5.46517243e-01 5.44164159e-01 5.36149950e-01
 5.31460421e-01 5.28870830e-01 5.20333153e-01 5.07951530e-01
 5.06153566e-01 5.02388798e-01 4.94790260e-01 4.89081554e-01
 4.75384169e-01 4.70801567e-01 4.57219021e-01 4.48136463e-01
 4.37723302e-01 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07
 4.75571308e-07 4.75571308e-07 4.75571308e-07 4.75571308e-07]